"use client";
import {UiText,useUiTranslation} from '@/lib/i18n/ui';

import {useState} from 'react';
import {ArrowUpRight,Check,Phone,Megaphone,CalendarDays,Mail} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {canManageModules} from '@/lib/roles';

const content={
 ringelister:{name:'Ringelister',title:'Flere gode samtaler. Mindre leting.',intro:'Finn aktuelle bedrifter, jobb deg gjennom listen og ta neste steg mens samtalen fortsatt er fersk.',benefits:['Finn aktuelle bedrifter fra Brønnøysundregistrene.','Kombiner fylker, steder, bransjer, antall ansatte og etableringsår.','Registrer samtalen, avtal et møte og flytt prospektet til kundekortet.'],caption:'Fra målrettet liste til neste kundesamtale.'},
 markedsforing:{name:'Markedsføring',title:'Hold kontakten. Bli husket.',intro:'Samle innlegg, e-post og innholdsplan i CRM-et. Nå kundene dine med et budskap som passer, og få oversikt over det dere har sendt og publisert.',benefits:['Skriv innhold én gang og publiser til tilkoblede kanaler.','Send e-post til utvalgte kundegrupper fra egen e-postkonto.','Samle planlagte e-poster, innlegg og resultater i én oversikt.'],caption:'Innhold og kundeutsendinger samlet på ett sted.'},
};

export function ModuleShowcase({moduleKey,role,price,onPurchase}:{moduleKey:keyof typeof content;role:string;price:number|null;onPurchase:()=>void}){
 const {ui}=useUiTranslation();
 const data=content[moduleKey],ring=moduleKey==='ringelister',canBuy=canManageModules(role),[expanded,setExpanded]=useState(false),Icon=ring?Phone:Megaphone;
 return <section className={`module-showcase ${ring?'module-showcase-ring':'module-showcase-marketing'}`}>
  <div className="module-showcase-copy"><span className="module-showcase-label"><Icon size={18}/>{ui(data.name)}<UiText text=" · Tilleggsmodul" /></span><h2>{ui(data.title)}</h2><p>{ui(data.intro)}</p><ul>{data.benefits.map(text=><li key={text}><Check size={17}/><span>{ui(text)}</span></li>)}</ul>
  <div className="module-showcase-action">{canBuy?<><p className="module-showcase-price">{price==null?ui("Ta kontakt med Noracre for å aktivere modulen."):<><strong>{price} kr</strong><UiText text=" per bruker / måned eks. mva." /></>}</p><Button disabled={price==null} onClick={onPurchase}><UiText text="Velg brukere og aktiver " /><ArrowUpRight size={17}/></Button></>:<div className="module-showcase-request"><strong><UiText text="Lyst til å bruke " />{ui(data.name)}?</strong><p><UiText text="Ta kontakt med administratoren i bedriften din for å få tilgang." /></p></div>}</div></div>
  <figure className={`module-showcase-figure ${expanded?'is-expanded':''}`}><div className="module-preview" role="img" aria-label={`${ui(data.name)}: ${ui(data.caption)} Illustrert med fiktive eksempeldata.`}><div className="module-preview-bar"><span><img src="/noracre-logo-primary.svg" alt="Noracre" width="94" height="26"/></span><span><UiText text="Eksempeldata" /></span></div>
  {ring?<><div className="module-preview-heading"><span><UiText text="RINGELISTER" /></span><h3><UiText text="Din neste samtale" /></h3><p><UiText text="Bedrifter i Vestland" /></p></div><div className="module-preview-filters"><span><UiText text="Bygg og håndverk" /></span><span><UiText text="5–30 ansatte" /></span></div><div className="module-preview-list">{[['Fjordbygg AS',ui("Bergen · 12 ansatte"),ui("Neste i listen")],['Vest Elektro AS',ui("Askøy · 8 ansatte"),ui("Ikke kontaktet")],['Nordvik Service AS',ui("Bergen · 16 ansatte"),ui("Ikke kontaktet")]].map(([name,detail,state],index)=><div className={index===0?'selected':''} key={name}><span className="module-preview-avatar">{name[0]}</span><div><strong>{name}</strong><small>{detail}</small></div><span>{state}</span></div>)}</div><div className="module-preview-call"><Phone size={18}/><div><strong><UiText text="En samtale. Et tydelig neste steg." /></strong><p><UiText text="Registrer resultat · Avtal møte · Legg til kunde" /></p></div></div></>:<><div className="module-preview-heading"><span><UiText text="MARKEDSFØRING" /></span><h3><UiText text="Innhold og utsendinger" /></h3></div><div className="module-preview-channels"><span><img src="/social/instagram.svg" alt=""/>Instagram</span><span><img src="/social/facebook.svg" alt=""/>Facebook</span><span><Mail size={15}/><UiText text="E-post" /></span></div><div className="module-preview-post"><span><UiText text="INNLEGG" /></span><p><UiText text="Små grep. Stor forskjell." /><br/><UiText text="Se hvordan vi hjelper bedrifter med en enklere hverdag." /></p><div><span>Instagram · Facebook</span><strong><UiText text="Publisert" /></strong></div></div><div className="module-preview-calendar"><CalendarDays size={22}/><div><strong><UiText text="Neste kundeutsending" /></strong><p><UiText text="Høstens nyheter · Kunder i Vestland" /></p></div><span><UiText text="Planlagt" /></span></div><div className="module-preview-plan"><span><UiText text="Innholdsplan" /></span><span><UiText text="Innlegg" /></span><span><UiText text="E-post" /></span></div></>}
  </div><figcaption>{ui(data.caption)}<button type="button" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?ui("Vis mindre"):ui("Se større")}</button></figcaption></figure>
 </section>;
}

