"use client";
import {UiText,useUiTranslation} from '@/lib/i18n/ui';

import {useCrmApi} from "@/lib/crm-api";
import {PartnerPaymentRegister} from "@/components/partner-payment-register";
import {billingHistory} from "@/lib/billing-history";
import {useEffect,useState} from "react";
import {Activity,Download,RefreshCw,ChevronRight,Search} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {invoicePage, type invoiceReport} from "@/lib/invoice-report";
import {Input} from "@/components/ui/input";
import type {BillingEvent} from "@/lib/operations-report";
import {operationsReport} from "@/lib/operations-report";
import {Collapsible,CollapsibleTrigger,CollapsibleContent} from "@/components/ui/collapsible";
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip} from "recharts";
import {useI18n} from '@/lib/i18n/react';
function useOperationsFormatting(){const i18n=useI18n(),{ui}=useUiTranslation();return {
 monthLabel:(s:string)=>i18n.calendarDate(s+'-01',{month:'long',year:'numeric'}),
 money:(n:number)=>i18n.money(n,{maximumFractionDigits:0}),
 date:(s:string)=>s?i18n.date(new Date(s),{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}):ui('Ikke registrert'),
 invoiceMoney:(ore:number)=>i18n.money(ore/100),number:i18n.number,calendarDate:i18n.calendarDate,
 };}
function csv(name:string,rows:(string|number)[][]){const text='\uFEFF'+rows.map(row=>row.map(v=>'"'+String(v).replace(/^[\s]*[=+@-]/,"'$&").replaceAll('"','""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
type Health={checkedAt:string;status:string;scope:string;checks:{name:string;ok:boolean;ms:number;detail:string}[]};
export function HealthStatus(){
 const {date,number}=useOperationsFormatting();
 const {ui}=useUiTranslation();
 const apiFetch=useCrmApi();

 const [open,setOpen]=useState(false),[health,setHealth]=useState<Health|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState('');
 async function check(){setBusy(true);setError(ui(''));try{const r=await apiFetch('/api/system-health');if(!r.ok)throw Error();setHealth(await r.json());}catch{setError(ui('Status kunne ikke kontrolleres. CRM eller innlogging kan være utilgjengelig. Prøv igjen.'));setHealth(null);}finally{setBusy(false);}}
 useEffect(()=>{check();},[]);
 const status=busy?'Kontrollerer …':error?'Ukjent':health?.status??'Ikke kontrollert';
 return <><button type="button" className={`server-health health-button ${status==='Normal'?'ok':'error'}`} onClick={()=>setOpen(true)} aria-label={ui("Systemstatus: {0}. Vis detaljer",{"0":ui(status)})}><Activity/><span><small><UiText text="Systemstatus" /></small><strong>{ui(status)}</strong></span><ChevronRight size={16}/></button>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle><UiText text="Systemstatus" /></DialogTitle><DialogDescription><UiText text="Reelle tilgjengelighetskontroller av CRM-tjenestene." /></DialogDescription></DialogHeader>
 {error&&<p role="alert">{error}</p>}{health&&<><p className="form-hint"><UiText text="Sist kontrollert: " />{date(health.checkedAt)}</p><div className="health-checks">{health.checks.map(c=><div key={c.name}><div><strong>{ui(c.name)}</strong><span className={c.ok?'health-good':'health-bad'}>{c.ok?ui("Tilgjengelig"):ui("Feil")} · {number(c.ms)} ms</span></div><p>{ui(c.detail)}</p></div>)}</div><p className="form-hint">{ui(health.scope)}</p></>}
 <Button type="button" disabled={busy} onClick={check}><RefreshCw size={16}/>{busy?ui("Kontrollerer …"):ui("Kontroller på nytt")}</Button></DialogContent></Dialog></>;
}
type Event=BillingEvent&{organizationName:string};
type Report=ReturnType<typeof operationsReport>&{events:Event[];invoices:ReturnType<typeof invoiceReport>};
export function OperationsInsights({organizationId}:{organizationId:number}){
 const {date,monthLabel,money,invoiceMoney,number,calendarDate}=useOperationsFormatting();
 const {ui}=useUiTranslation();
 const apiFetch=useCrmApi();

 const [data,setData]=useState<Report|null>(null),[error,setError]=useState(''),[org,setOrg]=useState('all'),[query,setQuery]=useState(''),[page,setPage]=useState(0),[historyOrg,setHistoryOrg]=useState<{id:number;name:string}|null>(null),[historyPage,setHistoryPage]=useState(0),[paymentOrg,setPaymentOrg]=useState<{id:number;name:string}|null>(null);
 async function load(){setError(ui(''));try{const r=await apiFetch('/api/operations');if(!r.ok)throw Error();setData(await r.json());}catch{setError(ui('Driftshistorikken kunne ikke hentes. Prøv igjen.'));}}
 useEffect(()=>{load();},[]);
 if(error)return <section className="surface"><p role="alert">{error}</p><Button onClick={load}><UiText text="Prøv igjen" /></Button></section>;
 if(!data)return <section className="surface"><p><UiText text="Laster aktiveringshistorikk …" /></p></section>;
 const options=[...new Map(data.events.map(e=>[e.organizationId,e.organizationName])).entries()];
 const events=data.events.filter(e=>org==='all'||e.organizationId===Number(org));
 const report=org==='all'?data:operationsReport(events);
 const invoices=data.invoices;
 const listing=invoicePage(invoices.rows,query,page);
 const historyUsers=new Map(data.events.filter(e=>e.organizationId===historyOrg?.id&&e.entityType==='user').sort((a,b)=>a.occurredAt.localeCompare(b.occurredAt)||a.id-b.id).map(e=>[e.membershipId||e.entityId,e.label]));
 const moduleLabel=(key:string)=>key==='ringelister'?ui('Ringelister'):key==='markedsforing'?ui('Markedsføring'):key;
 const history=historyOrg?billingHistory(data.events,historyOrg.id).map(e=>({...e,displayItem:e.entityType==='module'?moduleLabel(e.moduleKey):e.entityType==='license'?moduleLabel(e.moduleKey)+' · '+(historyUsers.get(e.membershipId)??ui('Bruker {0}',{'0':e.membershipId})):e.item})):[];
 const exportNumber=(value:number)=>number(value,{minimumFractionDigits:2,maximumFractionDigits:2,useGrouping:false});
 return <><Collapsible className="surface operations-history operations-fold"><CollapsibleTrigger className="operations-fold-trigger"><span><small><UiText text="UTVIKLING OVER TID" /></small><strong><UiText text="Månedsrapport" /></strong></span><ChevronRight size={20}/></CollapsibleTrigger><CollapsibleContent className="operations-fold-body"><div className="surface-head"><Button variant="outline" onClick={()=>csv(ui('noracre-manedsrapport.csv'),[['Måned','Bedrifter','Brukere','Moduler','Modultilganger','MRR NOK','Datagrunnlag'].map(header=>ui(header)),...report.months.map(m=>[monthLabel(m.month),...(m.available?[m.organizations,m.users,m.modules,m.licenses,m.mrr]:['','','','','']),ui(m.available?(m.partial?'Delvis historikk':m.current?'Hittil denne måneden':'Månedsslutt'):'Ingen historikk')])])}><Download size={16}/><UiText text="Eksporter rapport" /></Button></div>
 <div className="operations-report-filter"><span><UiText text="Bedrift" /></span><Select value={org} onValueChange={v=>{setOrg(v);setPage(0);}}><SelectTrigger aria-label={ui("Bedrift i driftsrapport")}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all"><UiText text="Alle bedrifter" /></SelectItem>{options.map(([id,name])=><SelectItem key={id} value={String(id)}>{name}</SelectItem>)}</SelectContent></Select></div>
 <p className="form-hint"><UiText text="Status ved månedsslutt (UTC), og hittil i inneværende måned. MRR er beregnet månedsbeløp. Beløpene er abonnementsverdi, ikke innbetalinger. CRM: bedriftens avtalte pris per aktiv bruker. Moduler: registrert pris per aktiv brukertilgang. Deaktiverte bedrifter og brukere teller ikke." /></p>
 <div className="operations-charts">{[{key:'mrr',title:'MRR',currency:true},{key:'users',title:ui("Aktive brukere")},{key:'organizations',title:ui("Aktive bedrifter")},{key:'modules',title:ui("Aktive moduler")}].map(metric=><section className="operations-chart" key={metric.key}><h4>{ui(metric.title)}</h4><ResponsiveContainer width="100%" height={230}><LineChart data={report.months.map(m=>({...m,label:monthLabel(m.month),value:m.available?m[metric.key as 'mrr'|'users'|'organizations'|'modules']:null}))} margin={{top:15,right:25,left:metric.currency?24:0,bottom:5}} accessibilityLayer><CartesianGrid stroke="var(--border)" strokeDasharray="3 5" vertical={false}/><XAxis dataKey="label" tick={{fill:'var(--muted-foreground)',fontSize:11}} tickFormatter={s=>s.slice(0,3)} minTickGap={12}/><YAxis allowDecimals={false} domain={[0,'auto']} tick={{fill:'var(--muted-foreground)',fontSize:11}} width={metric.currency?65:35}/><Tooltip contentStyle={{background:'var(--card)',color:'var(--foreground)',border:'1px solid var(--border)',borderRadius:12}} formatter={(v)=>[metric.currency?money(Number(v)):number(Number(v)),metric.title]}/><Line dataKey="value" name={metric.title} type="linear" stroke="#45b89b" strokeWidth={3} dot={{r:4,fill:'#45b89b'}} activeDot={{r:6}} connectNulls={false}/></LineChart></ResponsiveContainer><p className="form-hint">{report.months.filter(m=>m.available).length<2?ui("Første målepunkt er registrert. Linjen vokser etter hvert som flere måneder registreres."):ui("Manglende historikk vises som hull, ikke som null.")}</p></section>)}</div>
 <p className="form-hint"><UiText text="Full endringslogg fra " />{date(data.startedAt)}<UiText text=". Startstatus bygger på eksisterende registreringer; tidligere deaktiveringer og reaktiveringer kan ikke rekonstrueres sikkert." /></p></CollapsibleContent></Collapsible>
 <Collapsible className="surface operations-history operations-fold"><CollapsibleTrigger className="operations-fold-trigger"><span><small><UiText text="FAKTURAGRUNNLAG" /></small><strong><UiText text="Fakturering per bedrift" /></strong></span><ChevronRight size={20}/></CollapsibleTrigger><CollapsibleContent className="operations-fold-body">
 <div className="invoice-toolbar"><label className="invoice-search"><Search size={18}/><Input aria-label={ui("Søk etter bedrift i fakturagrunnlaget")} placeholder={ui("Søk etter bedrift …")} value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label><Button variant="outline" onClick={()=>csv(ui('noracre-fakturagrunnlag-{0}.csv',{'0':invoices.previousMonth}),[[ui('Bedrift'),ui('Til fakturering {0} NOK eks. mva.',{'0':monthLabel(invoices.previousMonth)}),ui('Opptjent {0} til {1} NOK eks. mva.',{'0':invoices.year,'1':calendarDate(invoices.throughDate)}),ui('Historikk')],...invoices.rows.filter(r=>r.organizationName.toLocaleLowerCase('nb').includes(query.trim().toLocaleLowerCase('nb'))).map(r=>[r.organizationName,r.previousComplete?exportNumber(r.previousOre/100):ui('Ufullstendig historikk'),exportNumber(r.ytdOre/100),ui(r.ytdComplete?'Komplett':'YTD viser kun kjent historikk')])])}><Download size={16}/><UiText text="Eksporter beløp" /></Button></div>
 <p className="form-hint"><UiText text="Avtalte priser eks. mva. per aktiv bruker og modultilgang. Aktivering, deaktivering og prisendringer gjelder fra neste kalenderdag, norsk tid. Beløpet fordeles på antall dager i måneden og avrundes samlet per bedrift til to desimaler." /></p>
 <div className="operations-table-scroll"><table className="operations-report-table invoice-table"><thead><tr><th scope="col"><UiText text="Bedrift" /></th><th scope="col"><UiText text="Til fakturering" /><small>{monthLabel(invoices.previousMonth)}</small></th><th scope="col"><UiText text="Opptjent hittil i " />{invoices.year}<small><UiText text="Til og med " />{calendarDate(invoices.throughDate)}</small></th></tr></thead><tbody>{listing.rows.map(row=><tr key={row.organizationId}><th scope="row"><button type="button" className="operations-company-button" onClick={()=>{setHistoryOrg({id:row.organizationId,name:row.organizationName});setHistoryPage(0);}}>{row.organizationName}</button><Button type="button" variant="ghost" size="sm" className="invoice-payment-button" aria-label={ui('Innbetalinger for {0}',{'0':row.organizationName})} onClick={()=>setPaymentOrg({id:row.organizationId,name:row.organizationName})}><UiText text="Innbetalinger" /></Button></th><td>{row.previousComplete?<strong>{invoiceMoney(row.previousOre)}</strong>:<span className="invoice-incomplete"><UiText text="Ufullstendig historikk" /></span>}</td><td><strong>{invoiceMoney(row.ytdOre)}</strong>{!row.ytdComplete&&<small><UiText text="Kun kjent historikk" /></small>}</td></tr>)}</tbody></table></div>
 {!listing.total&&<p role="status">{query?ui("Ingen bedrifter matcher søket."):ui("Ingen bedrifter registrert ennå.")}</p>}
 <div className="operations-log-pages"><span>{ui('{0} bedrifter · Side {1} av {2}',{'0':number(listing.total),'1':number(listing.page+1),'2':number(listing.pages)})}</span><Button variant="ghost" disabled={listing.page===0} onClick={()=>setPage(listing.page-1)}><UiText text="Forrige" /></Button><Button variant="ghost" disabled={listing.page+1>=listing.pages} onClick={()=>setPage(listing.page+1)}><UiText text="Neste" /></Button></div>
 <p className="form-hint"><UiText text="Opptjent hittil i år er fakturagrunnlag, ikke registrerte innbetalinger. Manglende eldre historikk merkes særskilt og beregnes ikke bakover fra dagens pris." /></p>
 </CollapsibleContent></Collapsible>
 <Dialog open={Boolean(paymentOrg)} onOpenChange={open=>{if(!open)setPaymentOrg(null);}}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle><UiText text="Innbetalinger – " />{paymentOrg?.name}</DialogTitle><DialogDescription><UiText text="Registrer mottatte betalinger og se grunnlaget for partnerprovisjon." /></DialogDescription></DialogHeader>{paymentOrg&&<PartnerPaymentRegister key={paymentOrg.id} companyId={paymentOrg.id} organizationId={organizationId}/>}</DialogContent></Dialog>
 <Dialog open={Boolean(historyOrg)} onOpenChange={open=>{if(!open)setHistoryOrg(null);}}><DialogContent className="billing-history-dialog"><DialogHeader><DialogTitle>{historyOrg?.name}<UiText text=" – abonnementshistorikk" /></DialogTitle><DialogDescription><UiText text="Aktivering, deaktivering og prisendringer for CRM-brukere og moduler. Tidspunktene vises i norsk tid." /></DialogDescription></DialogHeader>
 <Button variant="outline" onClick={()=>csv(ui('noracre-abonnementshistorikk.csv'),[['Tidspunkt','Type','Bruker / modul','Hendelse','Månedspris NOK'].map(header=>ui(header)),...history.map(e=>[date(e.occurredAt),ui(e.category),e.displayItem,ui(e.action),exportNumber(e.monthlyPrice)])])}><Download size={16}/><UiText text="Eksporter historikk" /></Button>
 <div className="billing-history-scroll"><table className="operations-report-table"><thead><tr><th><UiText text="Tidspunkt" /></th><th><UiText text="Bruker / modul" /></th><th><UiText text="Hendelse" /></th><th><UiText text="Avtalt månedspris" /></th></tr></thead><tbody>{history.slice(historyPage*40,(historyPage+1)*40).map(e=><tr key={e.id}><td data-label={ui("Tidspunkt")}>{date(e.occurredAt)}</td><td data-label={ui("Bruker / modul")}><strong>{e.displayItem}</strong><small>{ui(e.category)}</small></td><td data-label={ui("Hendelse")}>{ui(e.action)}{e.eventKind==='baseline'&&<small>{e.active?<UiText text="Aktiv" />:ui("Inaktiv")}<UiText text=" ved oppstart av historikken" />{e.referenceAt?ui(" · Opprinnelig registrert ")+date(e.referenceAt):''}</small>}</td><td data-label={ui("Avtalt månedspris")}>{e.entityType==='user'||e.entityType==='license'?<>{money(e.monthlyPrice)}{e.action==="Pris endret"&&<small><UiText text="Tidligere " />{money(e.previousPrice??0)}</small>}</>:'—'}</td></tr>)}</tbody></table>{!history.length&&<p><UiText text="Ingen historikk registrert." /></p>}</div>
 <div className="operations-log-pages"><span>{ui('{0} hendelser',{'0':number(history.length)})}</span><Button variant="ghost" disabled={!historyPage} onClick={()=>setHistoryPage(p=>p-1)}><UiText text="Forrige" /></Button><Button variant="ghost" disabled={(historyPage+1)*40>=history.length} onClick={()=>setHistoryPage(p=>p+1)}><UiText text="Neste" /></Button></div><p className="form-hint"><UiText text="Startstatus er en registrering av daværende tilstand. Eldre endringer som ikke ble loggført, vises ikke som sikre aktiveringsdatoer." /></p>
 </DialogContent></Dialog></>;
}
