"use client";
import {useEffect,useRef,useState} from 'react';import {apiFetch} from '@/lib/api-client';import {useI18n} from '@/lib/i18n/react';import {norwegianToday,paymentAmountOre,paymentCommission} from '@/lib/partner-payments';import {NorwegianDateInput} from '@/components/norwegian-date-input';import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Label} from '@/components/ui/label';
type Payment={id:number;reference:string;paidOn:string;amountOre:number;basisPoints:number;commissionOre:number;voidedAt:string};type Data={partner:{id:number;name:string;basisPoints:number|null}|null;payments:Payment[]};
export function PartnerPaymentRegister({companyId,organizationId}:{companyId:number;organizationId:number}){
 const {t,money,number,calendarDate}=useI18n(),[open,setOpen]=useState(false),[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[saved,setSaved]=useState(false),[reload,setReload]=useState(0),[busy,setBusy]=useState(false),[amount,setAmount]=useState(''),[reference,setReference]=useState(''),[paidOn,setPaidOn]=useState(norwegianToday),locked=useRef(false);
 const headers={'Content-Type':'application/json','x-organization-id':String(organizationId)};
 useEffect(()=>{if(!open)return;let cancelled=false;setData(null);setError('');apiFetch('/api/partner-payments?organizationId='+companyId,{headers:{'x-organization-id':String(organizationId)}}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||t('payment.error'));if(!cancelled)setData(d);}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[open,companyId,organizationId,reload,t]);
 async function submit(body:unknown,registration=false){if(locked.current)return;locked.current=true;setBusy(true);setError('');setSaved(false);try{const r=await apiFetch('/api/partner-payments',{method:'POST',headers,body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||t('payment.failed'));if(registration){setAmount('');setReference('');setSaved(true);}setReload(n=>n+1);}catch(e){setError(e instanceof Error?e.message:t('payment.failed'));}finally{locked.current=false;setBusy(false);}}
 const partner=data?.partner,rate=(bps:number)=>number(bps/10000,{style:'percent',maximumFractionDigits:2});let commission:number|null=null;try{if(partner?.basisPoints!=null)commission=paymentCommission(paymentAmountOre(amount),partner.basisPoints);}catch{}
 return <details className="payment-register" open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary>{t('payment.title')}</summary>{open&&<div className="organization-form">
 {partner?.basisPoints!=null?<><p>{t('payment.partner',{name:partner.name,rate:rate(partner.basisPoints)})}</p><Label>{t('payment.net')}</Label><Input aria-label={t('payment.net')} inputMode="decimal" value={amount} onChange={e=>{setAmount(e.target.value);setSaved(false);}} disabled={busy}/><Label>{t('payment.date')}</Label><NorwegianDateInput id={'received-'+companyId} label={t('payment.date')} value={paidOn} onChange={setPaidOn}/><Label>{t('payment.reference')}</Label><Input aria-label={t('payment.reference')} value={reference} maxLength={120} onChange={e=>setReference(e.target.value)} disabled={busy}/><p className="form-hint">{t('payment.referenceHint')} {t('payment.agreement')}</p>{commission!=null&&<strong>{t('commission.amount')}: {money(commission/100)}</strong>}<Button type="button" disabled={busy||commission==null||!reference.trim()||!paidOn} onClick={()=>submit({type:'payment',organizationId:companyId,amount,reference,paidOn,acceptedPartnerId:partner.id,acceptedBasisPoints:partner.basisPoints},true)}>{t(busy?'payment.saving':'payment.receipt')}</Button></>:data&&<p>{t('payment.missing')}</p>}
 {error&&<p role="alert">{error}</p>}{saved&&<p role="status">{t('payment.saved')}</p>}<Button type="button" variant="outline" disabled={busy} onClick={()=>setReload(n=>n+1)}>{t('payment.reload')}</Button>
 {data&&!data.payments.length&&<p>{t('payment.none')}</p>}{data?.payments.map(p=><article key={p.id} className="payment-record"><strong>{p.reference} · {money(p.amountOre/100)}</strong><small>{calendarDate(p.paidOn,{day:'numeric',month:'short',year:'numeric'})} · {t('commission.amount')}: {money(p.commissionOre/100)} ({rate(p.basisPoints)}){p.voidedAt?' · '+t('payment.voided'):''}</small><Button type="button" variant="ghost" disabled={busy} onClick={()=>{if(p.voidedAt||window.confirm(t('payment.voidConfirm')))void submit({type:'status',id:p.id,voided:!p.voidedAt});}}>{t(p.voidedAt?'payment.restore':'payment.void')}</Button></article>)}
 </div>}</details>;
}
