"use client";
import {useState} from 'react';
import { Input } from '@/components/ui/input';
export function ReminderFields({value,onChange}:{value:number[];onChange:(value:number[])=>void}){
 const [custom,setCustom]=useState<number[]>(value.flatMap((n,i)=>[5,15,30,60,120,1440,2880,10080].includes(n)?[]:[i]));
 return <fieldset className="reminder-fields"><legend>Varsling før oppfølging</legend><label>Antall varsler<select value={value.length} onChange={e=>onChange(Number(e.target.value)===0?[]:Number(e.target.value)===1?[value[0]??15]:[value[0]??1440,value[0]===15?1440:15])}><option value={0}>Ingen varsler</option><option value={1}>Ett varsel</option><option value={2}>To varsler</option></select></label>
 {value.map((minutes,index)=><label key={index}>Varsel {index+1}<select value={custom.includes(index)||![5,15,30,60,120,1440,2880,10080].includes(minutes)?'custom':minutes} onChange={e=>{setCustom(current=>e.target.value==='custom'?[...current,index]:current.filter(i=>i!==index));const next=[...value];next[index]=e.target.value==='custom'?1:Number(e.target.value);onChange(next);}}><option value={5}>5 minutter før</option><option value={15}>15 minutter før</option><option value={30}>30 minutter før</option><option value={60}>1 time før</option><option value={120}>2 timer før</option><option value={1440}>1 dag før</option><option value={2880}>2 dager før</option><option value={10080}>1 uke før</option><option value="custom">Egendefinert</option></select>{(custom.includes(index)||![5,15,30,60,120,1440,2880,10080].includes(minutes))&&<span><Input aria-label={`Minutter før for varsel ${index+1}`} type="number" min={1} max={43200} value={minutes} onChange={e=>{const next=[...value];next[index]=Number(e.target.value);onChange(next);}}/> minutter før</span>}</label>)}
 {value.length===2&&value[0]===value[1]&&<p role="alert">Velg ulike tidspunkter for de to varslene.</p>}<small>Varsler vises mens CRM-et er åpent. Nettleservarsler må være aktivert i innstillingene.</small></fieldset>;
}
