"use client";
import {UiText,useUiTranslation} from '@/lib/i18n/ui';
import {useCallback,useEffect,useState,useRef} from 'react';
import {useCrmApi} from '@/lib/crm-api';
import {canManageModules} from '@/lib/roles';
import {type RegisterCountry} from '@/lib/operating-countries';
import {HomeCountryPicker} from './home-country-picker';
import {useI18n} from '@/lib/i18n/react';
import {organizationLocale} from '@/lib/i18n/country';
import {OperatingCountryPicker} from './operating-country-picker';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from './ui/dialog';
import {toast} from 'sonner';
type List={id:number;name:string;country:RegisterCountry;createdByMembershipId:number};
type Assignment={id:number;listId:number;membershipId:number;assignedBy:string;acknowledgedAt:string};
type Source={code:RegisterCountry;name:string;source:string;ready:boolean;message:string};
type Metadata={homeCountry:string;lists:List[];assignments:Assignment[];operatingCountries:RegisterCountry[];sources:Source[]};
type Member={id:number;name:string;active:boolean};
export function SavedCallListManager({organizationId,role,members,currentMembershipId,country,onCountryChange,selectedListId,onSelect,refreshKey,onSourceReadyChange}:{organizationId:number;role:string;members:Member[];currentMembershipId:number;country:RegisterCountry;onCountryChange:(c:RegisterCountry)=>void;selectedListId:number|null;onSelect:(id:number|null)=>void;refreshKey:number;onSourceReadyChange?:(ready:boolean)=>void}){
 const {applyOrganizationLocale,locale}=useI18n(),{ui}=useUiTranslation();
 const countryNames=new Intl.DisplayNames([locale],{type:"region"});
 const [homeCountry,setHomeCountry]=useState("NO");
 const initializedOrganization=useRef<number|null>(null);
 const api=useCrmApi(),[meta,setMeta]=useState<Metadata|null>(null),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[names,setNames]=useState<Record<number,string>>({}),[targets,setTargets]=useState<Record<number,string>>({}),[countries,setCountries]=useState<RegisterCountry[]>(['NO']),[pending,setPending]=useState<Assignment[]>([]),[confirmDelete,setConfirmDelete]=useState<number|null>(null);
 const load=useCallback(async()=>{const r=await api('/api/saved-call-lists',{headers:{'x-organization-id':String(organizationId)}}),d=await r.json();if(!r.ok)throw Error(d.error||'Kunne ikke hente ringelister');return d as Metadata;},[api,organizationId]);
 useEffect(()=>{let cancelled=false;load().then(d=>{if(cancelled)return;if(initializedOrganization.current!==organizationId){initializedOrganization.current=organizationId;onCountryChange(d.operatingCountries.includes(d.homeCountry as RegisterCountry)?d.homeCountry as RegisterCountry:d.operatingCountries[0]);onSelect(null);}
setHomeCountry(d.homeCountry);setMeta(d);setCountries(d.operatingCountries);setNames(Object.fromEntries(d.lists.map(l=>[l.id,l.name])));setError('');setPending(d.assignments.filter(a=>a.membershipId===currentMembershipId&&!a.acknowledgedAt&&d.lists.some(l=>l.id===a.listId)));}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[load,refreshKey,currentMembershipId]);
 useEffect(()=>{if(!meta)return;const nextCountry=meta.sources.some(s=>s.code===country)?country:meta.operatingCountries[0];if(nextCountry!==country)onCountryChange(nextCountry);/* Recover available list after country changes. */const list=meta.lists.find(l=>l.id===selectedListId&&l.country===nextCountry);if(!list){const first=meta.lists.filter(l=>l.country===nextCountry).sort((a,b)=>b.id-a.id)[0];if((first?.id??null)!==selectedListId)onSelect(first?.id??null);}},[meta,country,selectedListId,onCountryChange,onSelect]);
 async function mutate(body:Record<string,unknown>){setBusy(true);try{const r=await api('/api/saved-call-lists',{method:'POST',headers:{'content-type':'application/json','x-organization-id':String(organizationId)},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error||'Kunne ikke lagre');const next=await load();setMeta(next);if(body.type==='countries')applyOrganizationLocale(organizationLocale(next.homeCountry),organizationId);if(body.type==='delete'&&body.listId===selectedListId)onSelect(null);setConfirmDelete(null);return true;}catch(e){toast.error(ui(e instanceof Error?e.message:'Kunne ikke lagre'));return false;}finally{setBusy(false);}}
 const source=meta?.sources.find(s=>s.code===country),selected=meta?.lists.find(l=>l.id===selectedListId);
 useEffect(()=>{if(source)onSourceReadyChange?.(source.ready);},[source?.ready,onSourceReadyChange]);
 return <>
 <div className="saved-list-toolbar">
 <label><UiText text="Registerland" /><select aria-label={ui("Registerland")} value={country} onChange={e=>{onCountryChange(e.target.value as RegisterCountry);onSelect(null);}}>{meta?.sources.map(s=><option value={s.code} key={s.code}>{countryNames.of(s.code)??s.name} · {s.source}</option>)}</select></label>
 <label><UiText text="Åpne ringeliste" /><select aria-label={ui("Åpne lagret ringeliste")} value={selectedListId??''} onChange={e=>onSelect(e.target.value?Number(e.target.value):null)}><option value=""><UiText text="Ingen lagret liste" /></option>{meta?.lists.filter(l=>l.country===country).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>
 <Button variant="outline" onClick={()=>setOpen(true)}><UiText text="Administrer ringelister" /></Button>
 </div>
 {error&&<p role="alert">{ui(error)}</p>}
 {source&&!source.ready&&<p role="status" className="form-hint">{ui(source.message)}<UiText text=" Du kan lagre og importere egne lister for dette landet." /></p>}
 {country!=='NO'&&<p className="form-hint">{country==='ZM'?<><UiText text="Zambiske leverandører kan importeres fra " /><a href="https://zepra.co.zm/open-data" target="_blank" rel="noreferrer">ZEPRA</a><UiText text=" eller " /><a href="https://data.open-contracting.org/en/publication/3" target="_blank" rel="noreferrer">ZPPA</a><UiText text=". Dette er ikke et fullstendig foretaksregister, og lisensen til opprinnelige kildeopplysninger må respekteres." /></>:country==='FR'?<UiText text="Franske virksomheter hentes fra Annuaire des Entreprises (INSEE/Sirene). Ansattall oppgis som intervaller, med årstallet når det er tilgjengelig." />:country==='NG'?<><UiText text="Nigeria kan bruke egne importerte ringelister. " /><a href="https://icrp.cac.gov.ng/public-search/" target="_blank" rel="noreferrer"><UiText text="CAC har offentlig manuelt selskapsoppslag" /></a><UiText text=", men automatisk søk krever lisensiert API." /></>:<>{source?.source}<UiText text=" tilbyr bedriftsdata, men antall ansatte er ofte ikke tilgjengelig." />{country==='GB'&&<> <a href="https://download.companieshouse.gov.uk/en_accountsdata.html" target="_blank" rel="noreferrer"><UiText text="Gratis britiske regnskapsfiler" /></a><UiText text=" kan brukes til egen ansattberikelse." /></>}{country==='IE'&&<><UiText text=" Contains Irish Public Sector Data licensed under the " /><a href="https://data.gov.ie/pages/licence" target="_blank" rel="noreferrer">Creative Commons Attribution 4.0 International licence</a>.</>}</>}</p>}
 {meta&&!meta.operatingCountries.includes(country)&&<p className="form-hint"><UiText text="Dette landet er ikke lenger valgt for bedriften. Lagrede lister kan fortsatt åpnes." /></p>}
 {selected&&<p className="form-hint"><UiText text="Åpen liste: " /><strong>{selected.name}</strong></p>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="saved-lists-dialog"><DialogHeader><DialogTitle><UiText text="Lagrede ringelister" /></DialogTitle><DialogDescription><UiText text="Åpne, gi nytt navn, slett eller deleger ringelister." /></DialogDescription></DialogHeader>
 {canManageModules(role)&&<section><HomeCountryPicker value={homeCountry} onChange={setHomeCountry}/><OperatingCountryPicker value={countries} onChange={setCountries}/><Button disabled={busy||!countries.length} onClick={()=>void mutate({type:'countries',homeCountry,operatingCountries:countries})}><UiText text="Lagre land" /></Button></section>}
 {!meta?.lists.length&&<p><UiText text="Ingen lagrede lister ennå. Nye og importerte lister lagres automatisk." /></p>}
 {meta?.lists.map(list=>{const manage=canManageModules(role)||list.createdByMembershipId===currentMembershipId;return <article className="saved-list-card" key={list.id}>
 <div><strong>{list.name}</strong><small>{countryNames.of(list.country)??list.country}</small></div>
 <Button disabled={busy} onClick={()=>{onCountryChange(list.country);onSelect(list.id);setOpen(false);}}><UiText text="Åpne" /></Button>
 {manage&&<><Input aria-label={ui("Navn på {0}",{"0":list.name})} value={names[list.id]??list.name} maxLength={120} onChange={e=>setNames({...names,[list.id]:e.target.value})}/><Button disabled={busy} variant="outline" onClick={()=>void mutate({type:'rename',listId:list.id,name:names[list.id]??list.name})}><UiText text="Lagre navn" /></Button>
 {confirmDelete===list.id?<><span><UiText text="Slette listen og ringehistorikken? Kundene beholdes." /></span><Button disabled={busy} variant="destructive" onClick={()=>void mutate({type:'delete',listId:list.id})}><UiText text="Bekreft sletting" /></Button><Button variant="outline" onClick={()=>setConfirmDelete(null)}><UiText text="Avbryt" /></Button></>:<Button disabled={busy} variant="outline" onClick={()=>setConfirmDelete(list.id)}><UiText text="Slett" /></Button>}</>}
 {canManageModules(role)&&<div className="saved-list-delegation"><select aria-label={ui("Deleger {0} til bruker",{"0":list.name})} value={targets[list.id]??''} onChange={e=>setTargets({...targets,[list.id]:e.target.value})}><option value=""><UiText text="Velg bruker" /></option>{members.filter(m=>m.active).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><Button disabled={busy||!targets[list.id]} onClick={()=>void mutate({type:'assign',listId:list.id,membershipId:Number(targets[list.id])})}><UiText text="Deleger" /></Button>{meta.assignments.filter(a=>a.listId===list.id).map(a=><div key={a.id}>{members.find(m=>m.id===a.membershipId)?.name??ui('Bruker')}<UiText text=" · delegert av " />{a.assignedBy}<Button size="sm" variant="outline" disabled={busy} onClick={()=>void mutate({type:'unassign',listId:list.id,membershipId:a.membershipId})}><UiText text="Fjern delegering" /></Button></div>)}</div>}
 </article>;})}</DialogContent></Dialog>
 <Dialog open={pending.length>0} onOpenChange={value=>{if(!value)void mutate({type:'acknowledge',ids:pending.map(a=>a.id)}).then(ok=>{if(ok)setPending([]);});}}><DialogContent><DialogHeader><DialogTitle><UiText text="Du har fått delegert ringelister" /></DialogTitle><DialogDescription><UiText text="Listene er tilgjengelige under lagrede ringelister." /></DialogDescription></DialogHeader>{pending.map(a=><p key={a.id}><strong>{meta?.lists.find(l=>l.id===a.listId)?.name}</strong><UiText text=" er delegert til deg av " /><strong>{a.assignedBy}</strong>.</p>)}<Button disabled={busy} onClick={()=>void mutate({type:'acknowledge',ids:pending.map(a=>a.id)}).then(ok=>{if(ok){const first=meta?.lists.find(l=>l.id===pending[0].listId);if(first){onCountryChange(first.country);onSelect(first.id);}setPending([]);}})}><UiText text="Åpne ringelisten" /></Button></DialogContent></Dialog>
 </>;
}
