import { env } from "cloudflare:workers";
import { and,desc,eq } from "drizzle-orm";
import { getDb } from "@/db";
import { attachments,companies } from "@/db/schema";
import { accessResponse,requireTenant } from "@/lib/tenant";

const bucket=()=>env.BUCKET as R2Bucket;

export async function GET(request:Request){try{const ctx=await requireTenant(request),params=new URL(request.url).searchParams,id=Number(params.get("id"));if(id){const[file]=await getDb().select().from(attachments).where(and(eq(attachments.id,id),eq(attachments.organizationId,ctx.organizationId))).limit(1);if(!file)return Response.json({error:"Vedlegget finnes ikke"},{status:404});const object=await bucket().get(file.objectKey);if(!object)return Response.json({error:"Filen finnes ikke"},{status:404});const safe=file.filename.replace(/[\r\n"]/g,"_");return new Response(object.body,{headers:{"content-type":file.contentType,"content-length":String(file.size),"content-disposition":`attachment; filename="${safe}"`}})}const companyId=Number(params.get("companyId"));if(!companyId)return Response.json({attachments:[]});const rows=await getDb().select({id:attachments.id,companyId:attachments.companyId,filename:attachments.filename,contentType:attachments.contentType,size:attachments.size,uploadedBy:attachments.uploadedBy,createdAt:attachments.createdAt}).from(attachments).where(and(eq(attachments.organizationId,ctx.organizationId),eq(attachments.companyId,companyId))).orderBy(desc(attachments.id));return Response.json({attachments:rows})}catch(e){return accessResponse(e)}}

export async function POST(request:Request){try{const ctx=await requireTenant(request),form=await request.formData(),companyId=Number(form.get("companyId")),file=form.get("file");if(!companyId||!(file instanceof File))return Response.json({error:"Velg en fil"},{status:400});if(file.size===0||file.size>10*1024*1024)return Response.json({error:"Filen må være mellom 1 byte og 10 MB"},{status:400});const[company]=await getDb().select({id:companies.id}).from(companies).where(and(eq(companies.id,companyId),eq(companies.organizationId,ctx.organizationId))).limit(1);if(!company)return Response.json({error:"Kunden finnes ikke"},{status:404});const filename=(file.name||"vedlegg").slice(0,180),key=`${ctx.organizationId}/${companyId}/${crypto.randomUUID()}`,contentType=file.type||"application/octet-stream";await bucket().put(key,await file.arrayBuffer(),{httpMetadata:{contentType}});try{const[created]=await getDb().insert(attachments).values({organizationId:ctx.organizationId,companyId,objectKey:key,filename,contentType,size:file.size,uploadedBy:ctx.user.displayName,createdAt:new Date().toISOString()}).returning();return Response.json({attachment:created},{status:201})}catch(e){await bucket().delete(key);throw e}}catch(e){return accessResponse(e)}}

export async function DELETE(request:Request){try{const ctx=await requireTenant(request),id=Number(new URL(request.url).searchParams.get("id"));if(!id)return Response.json({error:"Vedlegg mangler"},{status:400});const[file]=await getDb().select().from(attachments).where(and(eq(attachments.id,id),eq(attachments.organizationId,ctx.organizationId))).limit(1);if(!file)return Response.json({error:"Vedlegget finnes ikke"},{status:404});await bucket().delete(file.objectKey);await getDb().delete(attachments).where(and(eq(attachments.id,id),eq(attachments.organizationId,ctx.organizationId)));return Response.json({ok:true})}catch(e){return accessResponse(e)}}
