import {locales} from './i18n';
import {enquiryUserCounts} from './enquiry-options';
import {createI18n,type Locale} from './i18n';
import {localizePublicHtml,publicClientTranslations} from './public-site-i18n';
/** Public Noracre website. Kept separate from CRM authentication and application styles. */
type SiteEnv = { GOOGLE_DEMO_BOOKING_URL?: string };
const escape = (s: string) => s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const arrow='<span aria-hidden="true">↗</span>';
const nav=[['/crm','CRM'],['/moduler','Moduler'],['/om-noracre','Om Noracre'],['/kontakt','Kontakt']];
const icon=(name:string)=>`<span class="line-icon" aria-hidden="true">${({people:'◎',follow:'↗',notes:'≡',mail:'✉',phone:'↗',plan:'▦'} as Record<string,string>)[name]||'+'}</span>`;
const button=(label:string,href:string,kind='primary')=>`<a class="button ${kind}" href="${href}">${label}${arrow}</a>`;
const sectionLabel=(n:string,label:string)=>`<div class="eyebrow"><span>${n}</span>${label}</div>`;
const product=()=>`<div class="product-window" aria-label="Illustrasjon av kundeoppfølging i Noracre. Eksempeldata."><div class="product-bar"><img src="/noracre-logo-primary.svg" alt="Noracre" width="106" height="32"><span>Kunder & oppfølging</span><span class="sample-tag">Eksempel</span></div><div class="product-body"><div class="product-sidebar"><span class="mini-active">Kunder</span><span>Oppfølging</span><span>Tilbud</span><span>Rapporter</span><span>Ringelister</span><span>Markedsføring</span></div><div class="product-main"><div class="product-title"><div><small>KUNDEKORT</small><h3>Vest Kaffe AS</h3></div><span class="status-tag">Under oppfølging</span></div><div class="contact-example"><span class="avatar">IH</span><div><strong>Ingrid Hansen</strong><small>Daglig leder</small></div><span class="customer-label">Din kontakt</span></div><div class="example-note"><small>SISTE SAMTALE</small><p>Serviceavtalen for kaffemaskinene skal fornyes. Send forslag med levering av kaffe og to servicebesøk i året.</p></div><div class="next-meeting"><span class="date-tile"><strong>24</strong>TORSDAG</span><div><strong>Fornyelse av serviceavtale</strong><small>10:00 · Møte · Registrert av deg</small></div><span class="meeting-arrow" aria-hidden="true">↗</span></div></div></div><div class="product-bottom"><span>Kontakter</span><span>Notater</span><span>Vedlegg</span><span>Historikk</span><span>Alt på samme kundekort.</span></div></div>`;
const cta=(base:string)=>`<section class="closing wrap"><div>${sectionLabel('NESTE STEG','En prat er en god start')}<h2>Se om Noracre<br>passer for dere.</h2><p>Fortell oss hvordan dere jobber. Vi viser deg resten.</p></div><div class="closing-actions">${button('Book en demo',base+'/demo')}${button('Bli kunde',base+'/bli-kunde','outline')}<span>En gjennomgang tilpasset bedriften din.</span></div></section>`;
const form=(demo:boolean,base:string,locale:Locale)=>{
 const i18n=createI18n(locale);
 const t=(key:import('./i18n').MessageKey)=>escape(i18n.t(key));
 const messages=Object.fromEntries(['sending','sent','success','failed','timeout','networkError'].map(key=>[key,i18n.t(('enquiry.'+key) as import('./i18n').MessageKey)]));
 return `<form id="enquiry-form" class="enquiry-form" action="/api/public/enquiry" method="post" data-messages="${escape(JSON.stringify(messages))}" novalidate>
 <noscript><p>${t('enquiry.noScript')} <a href="mailto:jfn@noracre.no">jfn@noracre.no</a>.</p></noscript><input type="hidden" name="type" value="${demo?'demo':'customer'}">
 <div class="form-row"><label>${t('enquiry.company')}<input name="company" autocomplete="organization" required maxlength="160" placeholder="${t('enquiry.companyPlaceholder')}"></label><label>${t('enquiry.organizationNumber')} <span>${t('common.optional')}</span><input name="organizationNumber" inputmode="numeric" maxlength="12" placeholder="123 456 789"></label></div>
 <div class="form-row"><label>${t('enquiry.name')}<input name="name" autocomplete="name" required maxlength="120" placeholder="${t('enquiry.namePlaceholder')}"></label><label>${t('enquiry.email')}<input type="email" name="email" autocomplete="email" required maxlength="254" placeholder="${t('enquiry.emailPlaceholder')}"></label></div>
 <div class="form-row"><label>${t('enquiry.phone')} <span>${t('common.optional')}</span><input type="tel" name="phone" autocomplete="tel" maxlength="30" placeholder="${t('enquiry.phonePlaceholder')}"></label><label>${t('enquiry.users')}<select name="users" required><option value="">${t('enquiry.chooseUsers')}</option>${enquiryUserCounts.map(option=>`<option value="${option.value}">${t(option.label)}</option>`).join('')}</select></label></div>
 <label>${t(demo?'enquiry.demoMessage':'enquiry.customerMessage')} <span>${t('common.optional')}</span><textarea name="message" rows="4" maxlength="3000" placeholder="${t('enquiry.messagePlaceholder')}"></textarea></label>
 <div class="form-trap" aria-hidden="true"><label>${t('enquiry.trap')}<input name="website" tabindex="-1" autocomplete="off"></label></div>
 <p class="form-privacy">${t('enquiry.privacy')} <a href="${base}/personvern">${t('enquiry.readPrivacy')}</a>.</p><div id="form-status" class="form-status" role="status" aria-live="polite"></div>
 <button class="button primary" type="submit">${t(demo?'enquiry.submitDemo':'enquiry.submitCustomer')}${arrow}</button><p class="form-footnote">${t('enquiry.footnote')}</p></form>`;
};

function home(base:string){return `
<section class="energy-hero"><div class="wrap energy-layout"><div class="energy-copy"><span class="pill-label"><i></i> NORACRE CRM</span><h1>Kundene dine.<br><em>Hele veien.</em></h1><p>Fra første kontakt til neste oppdrag. Samle kundene, dialogen og alt som skal følges opp — på ett sted.</p><div class="energy-actions">${button('Se Noracre i en demo',base+'/demo')}${button('Dette får du',base+'/crm','light-outline')}</div><div class="hero-usecases"><span>Salg</span><span>Kundeservice</span><span>Oppfølging</span></div></div><div class="relationship-scene" aria-label="Eksempler på aktiviteter i Noracre"><svg class="scene-orbit" viewBox="0 0 600 600" aria-hidden="true"><circle cx="300" cy="300" r="210"/><circle cx="300" cy="300" r="280"/><path d="M40 450C170 100 440 590 560 150"/></svg><div class="scene-logo"><img src="/noracre-app-icon.svg" width="95" height="95" alt="Noracre"></div><div class="scene-card scene-customer"><span class="scene-symbol">↗</span><div><small>NY MULIGHET</small><strong>Fjordbygg AS</strong><span>Befaring avtalt · Torsdag 10:00</span></div></div><div class="scene-card scene-task"><span class="scene-symbol">✓</span><div><small>NESTE STEG</small><strong>Følg opp serviceavtalen</strong><span>Vest Kaffe · Ansvarlig: Emil</span></div></div><div class="scene-card scene-mail"><span class="scene-symbol">✉</span><div><small>DIALOGEN FORTSETTER</small><strong>Tilbud klart til sending</strong><span>Fra din egen e-postkonto</span></div></div><span class="scene-caption">Eksempler på kundeoppfølging</span><span class="scene-spark" aria-hidden="true">✳</span></div></div></section>
<div class="capability-ribbon"><div class="wrap"><span>Kundekort & kontakter</span><b>✦</b><span>Tilbud & e-post</span><b>✦</b><span>Påminnelser & møter</span><b>✦</b><span>Rapporter & historikk</span></div></div>
<section class="industry-section wrap"><div class="industry-intro"><span class="eyebrow">MANGE BRANSJER. SAMME BEHOV FOR OVERSIKT.</span><h2>Der dere har kunder,<br>har Noracre en plass.</h2><p>En befaring, en leveranse eller en avtale som skal fornyes. Det neste steget er forskjellig. Behovet for å huske det er det samme.</p><div class="industry-choices" aria-label="Velg et bransjeeksempel"><button type="button" data-industry="bygg" aria-pressed="true">Bygg & håndverk <span>↗</span></button><button type="button" data-industry="tjenester" aria-pressed="false">Rådgivning & tjenester <span>↗</span></button><button type="button" data-industry="handel" aria-pressed="false">Handel & leverandører <span>↗</span></button></div></div><div class="industry-story" data-industry-panel aria-live="polite"><span class="story-label" data-story="label">BYGG & HÅNDVERK · EKSEMPEL</span><span class="story-art" aria-hidden="true">↗</span><h3 data-story="heading">Fra befaring<br>til neste oppdrag.</h3><p data-story="body">Samle kontaktpersoner, befaringer, tilbud og vedlegg på kunden. Kollegaen som tar neste samtale, har historikken foran seg.</p><div class="story-next"><span>DETTE SKAL FØLGES OPP</span><strong data-story="task">Send pristilbud etter befaringen</strong><small data-story="detail">Fjordbygg AS · Ansvarlig: Emil · Fredag</small></div></div></section>
<section class="toolbox-section"><div class="wrap"><div class="toolbox-heading"><span class="eyebrow">EN ARBEIDSDAG. FÆRRE LØSE TRÅDER.</span><h2>Mer enn en kundeliste.</h2>${button('Utforsk funksjonene',base+'/crm','text-button')}</div><div class="toolbox-grid"><article class="toolbox-history"><span class="feature-kicker">KUNDEKORTET</span><h3>Alt dere vet.<br>Der dere trenger det.</h3><p>Kontaktpersoner, notater, vedlegg og tidligere aktiviteter følger kunden.</p><div class="mini-timeline"><div><i></i><span><strong>Telefon med kunden</strong><small>Behov og leveransedato avklart</small></span><b>09:15</b></div><div><i></i><span><strong>Tilbud lagt ved</strong><small>Klart for neste samtale</small></span><b>10:30</b></div><div><i></i><span><strong>Oppfølging planlagt</strong><small>Ansvarlig kollega er valgt</small></span><b>Fredag</b></div></div></article><article class="toolbox-mail"><span class="feature-kicker">TILBUD & E-POST</span><span class="feature-art" aria-hidden="true">↗</span><h3>Send mens<br>dialogen er varm.</h3><p>Bruk tilbudsmaler, legg ved filer og send fra din egen Google- eller Microsoft-konto.</p><div class="provider-pills"><span>Google</span><span>Microsoft</span></div></article><article class="toolbox-tasks"><span class="feature-kicker">OPPFØLGING</span><h3>Ingen «hvem skulle<br>ringe tilbake?»</h3><p>Avtal neste aktivitet, sett ansvarlig og få påminnelser.</p></article><article class="toolbox-reports"><span class="feature-kicker">RAPPORTER & OVERSIKT</span><h3>Se hva som skjer.</h3><p>Følg aktiviteter og medarbeidere. Ta med kundelisten fra Excel, og eksporter data ved behov.</p><div class="report-bars" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div></article></div></div></section>
<section class="growth-section wrap"><div class="growth-heading"><span class="eyebrow">BYGG VIDERE</span><h2>Nye muligheter.<br> <em>Samme arbeidsplass.</em></h2><p>Fra nye kundemuligheter til jevnlig kontakt. Utvid CRM-et med Ringelister og Markedsføring.</p></div><a class="growth-card calls" href="${base}/moduler#ringelister"><span class="growth-icon" aria-hidden="true">↗</span><small>RINGELISTER</small><h3>En god samtale<br>starter her.</h3><p>Finn aktuelle bedrifter og følg opp samtalene.</p><span class="growth-link">Se ringelister ${arrow}</span></a><a class="growth-card marketing" href="${base}/moduler#markedsforing"><span class="growth-icon" aria-hidden="true">✳</span><small>MARKEDSFØRING</small><h3>Hold kontakten.<br>Også mellom møtene.</h3><p>Publiser i sosiale kanaler og send e-post til kundegrupper.</p><span class="growth-link">Se markedsføring ${arrow}</span></a></section>
<section class="demo-banner"><div class="wrap"><span class="eyebrow">SE DET I PRAKSIS</span><h2>Ta med hverdagen deres.<br>Vi tar med Noracre.</h2><p>Se hvordan kundene, oppfølgingen og samarbeidet kan fungere hos dere.</p>${button('Book en demo',base+'/demo')}</div><span aria-hidden="true">↗</span></section>`;}

function crm(base:string){return `<section class="wrap page-hero">${sectionLabel('CRM','Kundekort · Tilbud · Aktiviteter · Rapporter')}<h1>Hele historien.<br><em>Før du sier hei.</em></h1><div class="page-lead"><p>Gi teamet en felles oversikt over kundene, dialogen og neste steg. Det skal være lett å komme i gang og lett å bruke videre.</p>${button('Book en demo',base+'/demo')}</div></section><section class="wrap product-section">${product()}</section><section class="section wrap feature-grid"><article>${icon('people')}<h2>Kunder og kontakter</h2><p>Samle bedrifter og kontaktpersonene deres på ett sted. Finn riktig person og se hvem dere har snakket med.</p></article><article>${icon('follow')}<h2>Neste oppfølging</h2><p>Planlegg møter og oppgaver med ansvarlig bruker. Se hva som skal gjøres, og hvilke kunder som trenger oppmerksomhet.</p></article><article>${icon('notes')}<h2>Notater og historikk</h2><p>Telefoner, møter og notater gir kollegaene dine sammenheng. Kundekortet viser hvordan relasjonen har utviklet seg.</p></article><article>${icon('mail')}<h2>E-post fra din konto</h2><p>Koble til Google eller Microsoft og send e-post fra CRM-et med din egen adresse som avsender.</p></article><article>${icon('notes')}<h2>Tilbud og vedlegg</h2><p>Bruk tilbudsmaler, tilpass teksten til kunden og legg ved dokumenter. Filer og kontaktinformasjon finnes på kundekortet.</p></article><article>${icon('plan')}<h2>Rapporter, import og eksport</h2><p>Følg med på aktiviteter og medarbeidere. Importer kundelister fra Excel og eksporter kundedata når dere trenger det.</p></article></section><section class="wrap statement"><span>ENKLERE SAMARBEID</span><h2>Én kunde.<br>Et helt team som er oppdatert.</h2><p>Den som tar neste samtale, skal ha historikken foran seg. Fra salg og rådgivning til leveranser og service: Alle jobber med den samme kundeinformasjonen.</p></section>${cta(base)}`;}
function modules(base:string){return `<section class="wrap page-hero">${sectionLabel('MODULER','Velg det dere trenger')}<h1>Et godt fundament.<br><em>Flere muligheter.</em></h1><div class="page-lead"><p>CRM-et samler kundene og oppfølgingen. Modulene gir dere flere måter å jobbe med dem på.</p><span class="quiet-note">Velg moduler per medarbeider.</span></div></section><section class="wrap module-detail" id="ringelister"><div class="module-index">01</div><div><span class="eyebrow">RINGELISTER</span><h2>Gjør neste samtale<br>enklere å ta.</h2><p>Jobb systematisk med bedrifter dere ønsker å komme i kontakt med. Hold oversikt underveis og ta dialogen videre inn i CRM-et.</p><ul class="plain-list"><li>Finn bedrifter etter sted, bransje og størrelse</li><li>Filtrer på flere steder og bransjer, ansatte og etableringsår</li><li>Bedriftsdata fra Brønnøysundregistrene og oppfølging i samme arbeidsflyt</li></ul>${button('Se ringelister i en demo',base+'/demo','outline')}</div><div class="module-card"><span class="eyebrow">DAGENS ARBEIDSFLYT</span><div><b>Finn bedriften</b><span>01</span></div><div><b>Ta kontakt</b><span>02</span></div><div><b>Registrer dialogen</b><span>03</span></div><div><b>Følg opp</b><span>04</span></div></div></section><section class="wrap module-detail" id="markedsforing"><div class="module-index">02</div><div><span class="eyebrow">MARKEDSFØRING</span><h2>Hold dialogen varm.<br>Også mellom møtene.</h2><p>Skriv innlegg, send e-post til kundegrupper og behold oversikten i innholdsplanen.</p><ul class="plain-list"><li>Publisering til tilkoblede kanaler</li><li>E-post fra din egen konto, nå eller senere</li><li>Søkbar innholdsplan med kommende og tidligere utsendinger</li></ul>${button('Snakk med oss om markedsføring',base+'/demo','outline')}</div><div class="module-card editorial-card"><span class="eyebrow">EN SAMLET INNHOLDSPLAN</span><h3>Planlegg.<br>Skriv.<br><em>Hold kontakten.</em></h3><span>INNLEGG + E-POST</span></div></section><section class="wrap pricing-note"><h2>CRM per bruker.<br>Moduler etter behov.</h2><div><p>Finn nye kunder med Ringelister. Hold kontakten med e-post og sosiale innlegg i Markedsføring.</p>${button('Få et tilbud',base+'/bli-kunde')}</div></section>${cta(base)}`;}
function about(base:string){return `<section class="wrap page-hero">${sectionLabel('OM NORACRE','Kunderelasjoner først')}<h1>Et CRM skal hjelpe.<br><em>Ikke stå i veien.</em></h1></section><section class="wrap founder-section"><div class="founder-mark"><img src="/noracre-app-icon.svg" alt="Noracre" width="360" height="360"><span>BYGGET MED SALGSARBEID I TANKENE</span></div><div><h2>Bygget for salgsarbeidet.</h2><p>Noracre bygger på erfaring fra salg og salgsledelse. Løsningen samler kundene, dialogen og oppfølgingen, slik at det er enklere å jobbe strukturert gjennom salgsdagen.</p><p>Noracre bygger på en enkel tanke: Det skal være lett å finne kunden, forstå historikken og ta neste steg. Også for dem som ikke har brukt et CRM før.</p><p>I en demo tar vi utgangspunkt i hvordan bedriften jobber. Du får se relevante funksjoner og et konkret forslag til hvordan Noracre kan brukes hos dere.</p>${button('Book en demo',base+'/demo','outline')}</div></section><section class="section wrap values"><h2>Dette vil vi gjøre enkelt.</h2><div class="workflow"><article><span class="step-number">01</span><h3>Å komme i gang.</h3><p>En oversiktlig vei fra spredte kundelister til et felles system.</p></article><article><span class="step-number">02</span><h3>Å holde oversikten.</h3><p>Kunder, kontaktpersoner og aktiviteter i en sammenheng.</p></article><article><span class="step-number">03</span><h3>Å få kontakt.</h3><p>Tydelige svar og hjelp til å finne en løsning som passer.</p></article></div></section>${cta(base)}`;}
function contact(base:string){return `<section class="wrap page-hero">${sectionLabel('KONTAKT','Du snakker med oss direkte')}<h1>La oss ta<br><em>en prat.</em></h1></section><section class="wrap contact-grid"><article><span class="eyebrow">SALG & SPØRSMÅL</span><h2>Kontakt Noracre</h2><p>Lurer du på om Noracre passer for bedriften din? Send en e-post, book en demo eller legg igjen en henvendelse.</p><a class="contact-email" href="mailto:jfn@noracre.no">jfn@noracre.no ${arrow}</a><p class="quiet-note">Vi svarer innen én virkedag.</p></article><div class="contact-choices"><a href="${base}/demo"><span>01</span><div><h3>Se Noracre i bruk</h3><p>En gjennomgang med rom for dine spørsmål.</p></div>${arrow}</a><a href="${base}/bli-kunde"><span>02</span><div><h3>Finn løsningen for dere</h3><p>Fortell oss litt om bedriften og behovene deres.</p></div>${arrow}</a></div></section>${cta(base)}`;}
function conversion(base:string,demo:boolean,booking:string,locale:Locale){return `<section class="wrap conversion"><div class="conversion-copy">${sectionLabel(demo?'DEMO':'BLI KUNDE',demo?'Se hvordan det fungerer':'Neste steg for bedriften din')}<h1>${demo?'Se Noracre.<br><em>Still spørsmål.</em>':'Bedre oversikt<br><em>starter her.</em>'}</h1><p>${demo?'En gjennomgang tilpasset bedriften din. Vi tar utgangspunkt i hvordan dere jobber og viser de delene som er relevante for dere.':'Fortell oss litt om bedriften din. Vi kontakter deg innen én virkedag for å avklare behovene og gi dere et tilpasset tilbud.'}</p><ol class="conversion-steps"><li><span>01</span>${demo?'Fortell oss hva dere trenger.':'Legg igjen kontaktinformasjonen din.'}</li><li><span>02</span>${demo?'Se kundekort, oppfølging og aktuelle moduler.':'Vi avklarer brukere og aktuelle moduler.'}</li><li><span>03</span>${demo?'Finn ut om Noracre passer for dere.':'Du får et tilbud før du bestemmer deg.'}</li></ol><div class="human-contact"><img src="/noracre-app-icon.svg" alt="" width="44" height="44"><div><strong>Noracre</strong><span>Demo, rådgivning og oppstart</span></div></div></div><div class="form-panel">${demo&&booking?`<span class="eyebrow">BOOK EN DEMO</span><h2>Finn en tid som passer.</h2><p>Velg et ledig tidspunkt for en demo. Du får bekreftelsen og møtedetaljene fra Google.</p>${button('Velg tidspunkt i Google Kalender',escape(booking))}<p class="form-footnote">Vil du heller avtale på e-post? <a href="mailto:jfn@noracre.no">Kontakt oss</a>.</p>`:`<span class="eyebrow">${demo?'AVTAL EN DEMO':'KONTAKTINFORMASJON'}</span><h2>${demo?'Vi finner en tid sammen.':'Hyggelig å bli kjent.'}</h2>${demo?'<p>Send oss en henvendelse, så kontakter vi deg for å avtale gjennomgangen.</p>':''}${form(demo,base,locale)}`}</div></section>`;}

export function publicWebsite(path:string,base='',env:SiteEnv={},locale:Locale='nb'):Response{
 const route=path.replace(/\/+$/,'')||'/';
 const booking=env.GOOGLE_DEMO_BOOKING_URL&&/^https:\/\/(calendar\.google\.com|calendar\.app\.google)\//.test(env.GOOGLE_DEMO_BOOKING_URL)?env.GOOGLE_DEMO_BOOKING_URL:'';
 const pages:Record<string,[string,string,()=>string]>={
 '/':['CRM for gode kunderelasjoner','Noracre samler kunder, oppfølging og salg. Book en personlig demo og få et tilbud tilpasset din bedrift.',()=>home(base)],
 '/crm':['Et enklere CRM','Samle kundekort, kontakter, historikk og neste oppfølging i Noracre CRM.',()=>crm(base)],
 '/moduler':['Moduler for salg og markedsføring','Utvid Noracre med ringelister og markedsføring. Velg løsningen som passer bedriften din.',()=>modules(base)],
 '/om-noracre':['Om Noracre','Et CRM bygget med salgsarbeid og kunderelasjoner i tankene. Les om Noracre.',()=>about(base)],
 '/personvern':['Personvern på nettsiden','Slik bruker Noracre opplysninger fra kontakt- og demoskjemaene.',()=>`<section class="wrap page-hero"><span class="eyebrow">PERSONVERN</span><h1>Opplysningene dine.</h1></section><section class="wrap website-privacy"><h2>Når du tar kontakt</h2><p>Noracre ved Joakim Ferdinand Nygård bruker opplysningene du sender inn til å besvare henvendelsen og følge opp ønsket om demo eller tilbud. Personvernkontakt: <a href="mailto:jfn@noracre.no">jfn@noracre.no</a>.</p><p>Skjemaet ber om bedrift, navn, e-post og antall brukere. Du kan også oppgi organisasjonsnummer, telefon og en melding. Ikke legg inn sensitive personopplysninger.</p><h2>Hvordan henvendelsen behandles</h2><p>Henvendelsen leveres til Noracres salgsinnboks via e-posttjenesten Resend. Nettsiden drives på Cloudflare. Kontaktopplysningene lagres i salgsinnboksen for oppfølging av henvendelsen. Nettsiden lagrer en teknisk sendereferanse og status for å håndtere gjentatte sendeforsøk, men ingen ekstra kopi av skjemainnholdet.</p><p>For å begrense misbruk brukes en hash av IP-adresse og tidsperiode i en midlertidig teknisk teller. Vi har ikke lagt inn annonsepiksler eller analyseverktøy på nettsiden.</p><h2>Formål og lagring</h2><p>Vi bruker kontaktopplysninger for å besvare og følge opp forespørsler, basert på vår berettigede interesse i å håndtere relevante henvendelser fra bedrifter. Dersom du selv er avtalepart, kan behandling som er nødvendig for å forberede eller oppfylle avtalen bygge på dette grunnlaget.</p><p>Opplysningene beholdes så lenge de er nødvendige for henvendelsen og eventuell videre kundedialog. Du kan be om at oppfølgingen avsluttes og opplysningene slettes. Opplysninger som må beholdes for lovpålagte plikter eller rettskrav, kan lagres videre til formålet er oppfylt.</p><h2>Demo i Google Kalender</h2><p>Når du åpner en bookinglenke til Google Kalender, håndteres valg av tidspunkt og booking av Google. Opplysningene du gir i bookingen blir tilgjengelige for møtearrangøren.</p><h2>Spørsmål om opplysningene dine</h2><p>Kontakt <a href="mailto:jfn@noracre.no">jfn@noracre.no</a> hvis du vil vite hvilke opplysninger vi har fra henvendelsen din, rette dem eller be om sletting.</p><p>Du kan også be om begrensning, protestere mot behandling basert på berettiget interesse og be om dataportabilitet når vilkårene er oppfylt. Du kan klage til <a href="https://www.datatilsynet.no/">Datatilsynet</a>.</p><p>For bruk av selve CRM-et gjelder <a href="https://crm.noracre.no/personvern">personvernerklæringen for Noracre CRM</a>.</p></section>`],
 '/kontakt':['Kontakt oss','Kontakt Noracre om CRM, demo og tilbud. Vi svarer innen én virkedag.',()=>contact(base)],
 '/bli-kunde':['Bli kunde','Fortell oss om bedriften din. Noracre kontakter deg innen én virkedag.',()=>conversion(base,false,booking,locale)],
 '/demo':['Book en demo','Se Noracre CRM i en gjennomgang tilpasset bedriften din.',()=>conversion(base,true,booking,locale)]};
 const page=pages[route];
 const body=page?page[2]():`<section class="wrap page-hero"><span class="eyebrow">404</span><h1>Her var det<br><em>ingen side.</em></h1>${button('Til forsiden',base+'/')}</section>`;
 const title=(page?.[0]||'Siden finnes ikke')+' | Noracre';
let html=`<!doctype html><html lang="${locale}" dir="${locales[locale].direction}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${escape(page?.[1]||'Noracre CRM')}"><meta name="theme-color" content="#063b3a"><link rel="icon" href="/favicon.svg"><link rel="canonical" href="https://noracre.no${route==='/'?'':route}${locale==='en'?'?lang=en':''}"><link rel="alternate" hreflang="nb" href="https://noracre.no${route==='/'?'':route}"><link rel="alternate" hreflang="en" href="https://noracre.no${route==='/'?'':route}?lang=en"><meta property="og:title" content="${title}"><meta property="og:description" content="${escape(page?.[1]||'Noracre CRM')}"><meta property="og:type" content="website"><link rel="stylesheet" href="/website/site.css?v=6"><script defer src="/website/site.js?v=5"></script></head><body><a class="skip-link" href="#main">Hopp til innhold</a><header class="site-header"><div class="header-inner"><a class="wordmark" href="${base}/" aria-label="Noracre – forsiden"><img src="/noracre-logo-primary.svg" alt="Noracre" width="156" height="45"></a><nav class="desktop-nav" aria-label="Hovedmeny">${nav.map(([url,name])=>`<a href="${base+url}"${route===url?' aria-current="page"':''}>${name}</a>`).join('')}</nav><div class="header-actions"><div class="language-switch" aria-label="Language"><a href="${base+route}?lang=nb" lang="nb" hreflang="nb" aria-label="Norsk"${locale==='nb'?' aria-current="true"':''}>🇳🇴 <span>Norsk</span></a><a href="${base+route}?lang=en" lang="en" hreflang="en" aria-label="English"${locale==='en'?' aria-current="true"':''}>🇬🇧 <span>English</span></a></div><a class="login" href="https://crm.noracre.no">Logg inn ${arrow}</a>${button('Bli kunde',base+'/bli-kunde','primary compact')}<button class="menu-toggle" aria-expanded="false" aria-controls="mobile-nav" aria-label="Åpne meny"><span></span><span></span></button></div></div><nav id="mobile-nav" class="mobile-nav" aria-label="Mobilmeny" hidden>${nav.map(([url,name])=>`<a href="${base+url}">${name}</a>`).join('')}<a href="${base}/demo">Book en demo</a></nav></header><main id="main">${body}</main><footer><div class="wrap footer-top"><div><a href="${base}/"><img src="/noracre-logo-dark.svg" alt="Noracre – forsiden" width="200" height="60"></a><p>God oppfølging.<br>Gode relasjoner.</p></div><nav aria-label="Produkt"><strong>Noracre</strong>${nav.map(([url,name])=>`<a href="${base+url}">${name}</a>`).join('')}</nav><nav aria-label="Kom i gang"><strong>La oss snakkes</strong><a href="${base}/demo">Book en demo</a><a href="${base}/bli-kunde">Bli kunde</a><a href="https://crm.noracre.no">Logg inn i CRM</a></nav></div><div class="wrap footer-bottom"><span>© ${new Date().getFullYear()} Noracre</span><div><a href="${base}/personvern">Personvern</a><a href="https://crm.noracre.no/vilkar">Vilkår</a></div><span>Bygget for gode kunderelasjoner.</span></div></footer></body></html>`;
 html=localizePublicHtml(html,locale,base);
 const translations=JSON.stringify(publicClientTranslations(locale)).replace(/</g,'\\u003c');
 html=html.replace('</body>',`<script id="site-translations" type="application/json">${translations}</script></body>`);
 return new Response(html,{status:page?200:404,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'private, max-age=0', 'Vary':'Cookie', 'Content-Language':locale,'X-Robots-Tag':base?'noindex, nofollow':'index, follow'}});
}
