import {outboundCompanyIds,requireOutboundCompany} from "@/lib/outbound-company-access";
import {validateReminderMinutes} from "@/lib/followup-reminder";
import { actorJson, actorRef } from "@/lib/actor-names";
import {syncNextFollowup} from "@/lib/followups";
import { and,desc,eq,inArray } from "drizzle-orm";
import { getDb } from "@/db";
import { activities,companies,contacts } from "@/db/schema";
import { AccessError,accessResponse,requireTenant } from "@/lib/tenant";
function reminders(value:unknown){try{return JSON.stringify(validateReminderMinutes(value??[15]));}catch(e){throw new AccessError(400,(e as Error).message);}}
export async function GET(request:Request){try{const ctx=await requireTenant(request),allowed=await outboundCompanyIds(ctx);return await actorJson(ctx,{activities:await getDb().select().from(activities).where(and(eq(activities.organizationId,ctx.organizationId),allowed?inArray(activities.companyId,allowed.query):undefined,new URL(request.url).searchParams.has("companyId")?eq(activities.companyId,Number(new URL(request.url).searchParams.get("companyId"))):undefined)).orderBy(desc(activities.createdAt))})}catch(e){return accessResponse(e)}}
export async function POST(request:Request){try{const ctx=await requireTenant(request),data=await request.json() as Record<string,unknown>,now=new Date().toISOString(),companyId=Number(data.companyId),isTask=data.isTask===true,db=getDb();await requireOutboundCompany(ctx,companyId);const reminderMinutes=reminders(data.reminderMinutes);if(isTask&&(!data.dueAt||!Number.isFinite(Date.parse(String(data.dueAt)))))throw new AccessError(400,"Velg en gyldig dato");const [parent]=await db.select().from(companies).where(and(eq(companies.id,companyId),eq(companies.organizationId,ctx.organizationId))).limit(1);if(!parent)throw new AccessError(404,"Kunden finnes ikke");if(typeof data.contactId==="number"){const [contact]=await db.select().from(contacts).where(and(eq(contacts.id,data.contactId),eq(contacts.companyId,companyId),eq(contacts.organizationId,ctx.organizationId))).limit(1);if(!contact)throw new AccessError(404,"Kontaktpersonen finnes ikke");}const [activity]=await db.insert(activities).values({organizationId:ctx.organizationId,companyId,contactId:typeof data.contactId==="number"?data.contactId:null,companyName:String(data.companyName??""),kind:String(data.kind??"Annet"),note:String(data.note??""),dueAt:String(data.dueAt??""),reminderMinutes,completedAt:isTask?"":String(data.completedAt??now),createdBy:actorRef(ctx.user),createdAt:now}).returning();let followup=null;const nextActionDate=String(data.nextActionDate??"");if(!isTask&&nextActionDate){[followup]=await db.insert(activities).values({organizationId:ctx.organizationId,companyId,contactId:typeof data.contactId==="number"?data.contactId:null,companyName:String(data.companyName??""),kind:String(data.followupKind??"Annet"),note:String(data.nextAction??"Følg opp"),dueAt:nextActionDate,reminderMinutes,completedAt:"",createdBy:actorRef(ctx.user),createdAt:now}).returning()}if(companyId>0)await db.update(companies).set({...(isTask?{}:{lastContactAt:now}),nextAction:String(data.nextAction??""),nextActionDate,updatedAt:now}).where(and(eq(companies.id,companyId),eq(companies.organizationId,ctx.organizationId)));await syncNextFollowup(ctx.organizationId,companyId);return await actorJson(ctx,{activity,followup},{status:201})}catch(e){return accessResponse(e)}}
export async function PATCH(request:Request){try{
 const ctx=await requireTenant(request),data=await request.json() as Record<string,unknown>,id=Number(data.id),db=getDb();
 const [existing]=await db.select().from(activities).where(and(eq(activities.id,id),eq(activities.organizationId,ctx.organizationId))).limit(1);
 if(!existing)throw new AccessError(404,"Oppfølgingen finnes ikke");
 await requireOutboundCompany(ctx,existing.companyId);
 const changes:Partial<typeof activities.$inferInsert>={};
 if(Object.hasOwn(data,"reminderMinutes"))changes.reminderMinutes=reminders(data.reminderMinutes);
 if(Object.hasOwn(data,"completedAt"))changes.completedAt=String(data.completedAt);
 if(Object.hasOwn(data,"dueAt")){if(!data.dueAt||!Number.isFinite(Date.parse(String(data.dueAt))))throw new AccessError(400,"Velg en gyldig dato");changes.dueAt=String(data.dueAt);}
 if(Object.hasOwn(data,"note"))changes.note=String(data.note).trim();
 if(Object.hasOwn(data,"contactId")){changes.contactId=data.contactId===null?null:Number(data.contactId);if(changes.contactId!==null){const [c]=await db.select().from(contacts).where(and(eq(contacts.id,changes.contactId),eq(contacts.companyId,existing.companyId),eq(contacts.organizationId,ctx.organizationId))).limit(1);if(!c)throw new AccessError(404,"Kontaktpersonen finnes ikke");}}
 const [activity]=await db.update(activities).set(changes).where(and(eq(activities.id,id),eq(activities.organizationId,ctx.organizationId))).returning();
 await syncNextFollowup(ctx.organizationId,existing.companyId);return await actorJson(ctx,{activity});
}catch(e){return accessResponse(e)}}
export async function DELETE(request:Request){try{const ctx=await requireTenant(request),id=Number(new URL(request.url).searchParams.get("id"));if(!id)return await actorJson(ctx,{error:"Hendelse mangler"},{status:400});const[existing]=await getDb().select().from(activities).where(and(eq(activities.id,id),eq(activities.organizationId,ctx.organizationId))).limit(1);if(existing)await requireOutboundCompany(ctx,existing.companyId);const[removed]=await getDb().delete(activities).where(and(eq(activities.id,id),eq(activities.organizationId,ctx.organizationId))).returning();if(!removed)return await actorJson(ctx,{error:"Hendelsen finnes ikke"},{status:404});await syncNextFollowup(ctx.organizationId,removed.companyId);return await actorJson(ctx,{ok:true})}catch(e){return accessResponse(e)}}


