import { and,desc,eq } from "drizzle-orm";
import { getDb } from "@/db";
import { activities,companies,contacts } from "@/db/schema";
import { accessResponse,requireTenant } from "@/lib/tenant";
function values(data:Record<string,unknown>,organizationId:number){const now=new Date().toISOString();return{organizationId,customerType:String(data.customerType??"Bedrift"),name:String(data.name??"").trim(),orgNumber:String(data.orgNumber??""),contactName:String(data.contactName??""),phone:String(data.phone??""),email:String(data.email??""),stage:String(data.stage??"Ny kunde"),nextAction:String(data.nextAction??""),nextActionDate:String(data.nextActionDate??""),nextContactId:typeof data.nextContactId==="number"?data.nextContactId:null,note:String(data.note??""),industry:String(data.industry??""),city:String(data.city??""),employees:typeof data.employees==="number"?data.employees:null,revenue:typeof data.revenue==="number"?data.revenue:null,source:String(data.source??"Manuelt"),assignedTo:String(data.assignedTo??""),lastContactAt:String(data.lastContactAt??""),syncedAt:String(data.syncedAt??""),createdAt:String(data.createdAt??now),updatedAt:now}}
export async function GET(request:Request){try{const ctx=await requireTenant(request);return Response.json({companies:await getDb().select().from(companies).where(eq(companies.organizationId,ctx.organizationId)).orderBy(desc(companies.id)).limit(1000),context:ctx})}catch(e){return accessResponse(e)}}
export async function POST(request:Request){try{const ctx=await requireTenant(request),data=await request.json() as Record<string,unknown>&{companies?:Record<string,unknown>[]},db=getDb();if(Array.isArray(data.companies)){const rows=data.companies.slice(0,500).map(x=>values({...x,nextContactId:null,assignedTo:x.assignedTo||ctx.user.displayName},ctx.organizationId)).filter(x=>x.name);const inserted=await db.insert(companies).values(rows).returning();return Response.json({companies:inserted},{status:201})}const row=values({...data,nextContactId:null,assignedTo:data.assignedTo||ctx.user.displayName},ctx.organizationId);if(!row.name)return Response.json({error:"Bedriftsnavn mangler"},{status:400});const [company]=await db.insert(companies).values(row).returning();if(row.contactName)await db.insert(contacts).values({organizationId:ctx.organizationId,companyId:company.id,name:row.contactName,title:"",phone:row.phone,email:row.email,isPrimary:true,createdAt:new Date().toISOString()});return Response.json({company},{status:201})}catch(e){return accessResponse(e)}}
export async function PATCH(request:Request){try{const ctx=await requireTenant(request),data=await request.json() as Record<string,unknown>,id=Number(data.id);if(!id)return Response.json({error:"Kunde mangler"},{status:400});const db=getDb(),row=values(data,ctx.organizationId);if(row.nextContactId!==null){const [contact]=await db.select().from(contacts).where(and(eq(contacts.id,row.nextContactId),eq(contacts.companyId,id),eq(contacts.organizationId,ctx.organizationId))).limit(1);if(!contact)return Response.json({error:"Kontaktpersonen finnes ikke"},{status:404});}const [company]=await db.update(companies).set({...row,createdAt:undefined,nextAction:undefined,nextActionDate:undefined,nextContactId:undefined}).where(and(eq(companies.id,id),eq(companies.organizationId,ctx.organizationId))).returning();if(!company)return Response.json({error:"Kunden finnes ikke"},{status:404});return Response.json({company})}catch(e){return accessResponse(e)}}


