import { actorJson, actorRef, assignmentRef } from "@/lib/actor-names";
import { and,desc,eq } from "drizzle-orm";
import { getDb } from "@/db";
import { companies,contacts } from "@/db/schema";
import { AccessError,accessResponse,requireTenant } from "@/lib/tenant";
import {normalizeRegistryId} from "@/lib/prospect-import";
function values(data:Record<string,unknown>,organizationId:number){const now=new Date().toISOString(),country=String(data.country??"NO").toUpperCase();if(!/^[A-Z]{2}$/.test(country))throw new AccessError(400,"Velg et gyldig land.");return{organizationId,country,customerType:String(data.customerType??"Bedrift"),name:String(data.name??"").trim(),orgNumber:normalizeRegistryId(data.orgNumber,country),contactName:String(data.contactName??""),phone:String(data.phone??""),email:String(data.email??""),stage:String(data.stage??"Ny kunde"),nextAction:String(data.nextAction??""),nextActionDate:String(data.nextActionDate??""),nextContactId:typeof data.nextContactId==="number"?data.nextContactId:null,note:String(data.note??""),industry:String(data.industry??""),city:String(data.city??""),address:String(data.address??""),postalCode:String(data.postalCode??""),employeeRange:String(data.employeeRange??"").slice(0,40),employeeRangeYear:/^\d{4}$/.test(String(data.employeeRangeYear??""))?String(data.employeeRangeYear):"",employees:typeof data.employees==="number"?data.employees:null,revenue:typeof data.revenue==="number"?data.revenue:null,source:String(data.source??"Manuelt"),assignedTo:String(data.assignedTo??""),lastContactAt:String(data.lastContactAt??""),syncedAt:String(data.syncedAt??""),createdAt:String(data.createdAt??now),updatedAt:now}}
export async function GET(request:Request){try{const ctx=await requireTenant(request),db=getDb();
 const rows=await db.select().from(companies).where(eq(companies.organizationId,ctx.organizationId)).orderBy(desc(companies.id));
 // Keep each contact available to customer search, not only the primary contact.
 const people=rows.length?await db.select({companyId:contacts.companyId,name:contacts.name,title:contacts.title,email:contacts.email,phone:contacts.phone}).from(contacts).where(eq(contacts.organizationId,ctx.organizationId)):[];
 const byCompany=new Map<number,typeof people>();
 for(const person of people){const list=byCompany.get(person.companyId)??[];list.push(person);byCompany.set(person.companyId,list);}
 return await actorJson(ctx,{companies:rows.map(company=>({...company,searchContacts:byCompany.get(company.id)??[]})),context:ctx});
}catch(e){return accessResponse(e)}}
export async function POST(request:Request){try{const ctx=await requireTenant(request),data=await request.json() as Record<string,unknown>&{companies?:Record<string,unknown>[]},db=getDb();if(Array.isArray(data.companies)){const rows=(await Promise.all(data.companies.slice(0,500).map(async x=>values({...x,nextContactId:null,assignedTo:x.assignedTo&&x.assignedTo!==ctx.user.displayName?await assignmentRef(ctx.organizationId,String(x.assignedTo)):actorRef(ctx.user)},ctx.organizationId)))).filter(x=>x.name);const inserted=await db.insert(companies).values(rows).returning();return await actorJson(ctx,{companies:inserted},{status:201})}const row=values({...data,nextContactId:null,assignedTo:data.assignedTo&&data.assignedTo!==ctx.user.displayName?await assignmentRef(ctx.organizationId,String(data.assignedTo)):actorRef(ctx.user)},ctx.organizationId);if(!row.name)return await actorJson(ctx,{error:"Bedriftsnavn mangler"},{status:400});const [company]=await db.insert(companies).values(row).returning();if(row.contactName)await db.insert(contacts).values({organizationId:ctx.organizationId,companyId:company.id,name:row.contactName,title:"",phone:row.phone,email:row.email,isPrimary:true,createdAt:new Date().toISOString()});return await actorJson(ctx,{company},{status:201})}catch(e){return accessResponse(e)}}
export async function PATCH(request:Request){try{const ctx=await requireTenant(request),data=await request.json() as Record<string,unknown>,id=Number(data.id);if(!id)return await actorJson(ctx,{error:"Kunde mangler"},{status:400});const db=getDb(),row=values(data,ctx.organizationId);const [previous]=await db.select({assignedTo:companies.assignedTo,country:companies.country,address:companies.address,postalCode:companies.postalCode,employeeRange:companies.employeeRange,employeeRangeYear:companies.employeeRangeYear,source:companies.source}).from(companies).where(and(eq(companies.id,id),eq(companies.organizationId,ctx.organizationId))).limit(1);if(!previous)return await actorJson(ctx,{error:"Kunden finnes ikke"},{status:404});for(const key of ["country","address","postalCode","employeeRange","employeeRangeYear","source"] as const)if(!Object.hasOwn(data,key))row[key]=previous[key];row.assignedTo=Object.hasOwn(data,"assignedTo")?await assignmentRef(ctx.organizationId,String(data.assignedTo??""),previous.assignedTo):previous.assignedTo;if(row.nextContactId!==null){const [contact]=await db.select().from(contacts).where(and(eq(contacts.id,row.nextContactId),eq(contacts.companyId,id),eq(contacts.organizationId,ctx.organizationId))).limit(1);if(!contact)return await actorJson(ctx,{error:"Kontaktpersonen finnes ikke"},{status:404});}const [company]=await db.update(companies).set({...row,createdAt:undefined,nextAction:undefined,nextActionDate:undefined,nextContactId:undefined}).where(and(eq(companies.id,id),eq(companies.organizationId,ctx.organizationId))).returning();if(!company)return await actorJson(ctx,{error:"Kunden finnes ikke"},{status:404});return await actorJson(ctx,{company})}catch(e){return accessResponse(e)}}


