import {and,asc,desc,eq,gt,gte,inArray,isNull,lte,ne,or,sql,getTableColumns,type SQL,type SQLWrapper} from 'drizzle-orm';
import {alias,type AnySQLiteTable} from 'drizzle-orm/sqlite-core';
import {getDb} from '@/db';
import {callListEntries,callListAssignments,savedCallLists,companies,memberships,moduleLicenses,organizations,outboundLeadState,outboundCallLogs,outboundDeals,outboundDealPayments,outboundCompanyOwnership,outboundSuppression} from '@/db/schema';
import {AccessError,accessResponse,requireTenant} from '@/lib/tenant';
import {accessibleLists,requireList} from '@/lib/saved-call-lists';
import {canManageModules,requireModuleAccess} from '@/lib/module-access';
import {normalizeRegistryId} from '@/lib/prospect-import';
import {outboundCompanyScope,requireOutboundCompany} from '@/lib/outbound-company-access';
import {homeCountries} from '@/lib/home-countries';
import {outboundCompanyKey,outboundRegistryExpression} from '@/lib/outbound-identity';
import {normalizeOutboundRules,eligibleForOutbound} from '@/lib/outbound-markets';
import {validateCommissionPolicy,validateReceivedAt,paymentReferenceKey,commissionEligibility,receivedCommission,refundCommission} from '@/lib/outbound-commission';
const outcomes=['Ikke svar','Sentralbord','Feil nummer','Beslutningstaker kontaktet','Interessert','Ikke interessert','Møte booket','Reservert mot kontakt'] as const;
const stages=['Prospekt','Demo booket','Demo gjennomført','Prøveperiode','Tilbud','Kunde','Tapt'] as const;
const conversationOutcomes=['Beslutningstaker kontaktet','Interessert','Ikke interessert','Møte booket'];
const json=(value:unknown,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'private, no-store'}});
const integer=(v:unknown,min=0,max=100000000)=>Number.isSafeInteger(v)&&Number(v)>=min&&Number(v)<=max;
const clean=(value:unknown,max=500)=>String(value??'').trim().slice(0,max);
const manager=(role:string)=>canManageModules(role);
const isoDate=(value:unknown)=>{
 if(typeof value!=='string'||value.length>=40||!/^\d{4}-\d{2}-\d{2}T(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d{1,3})?)?(?:Z|[+-](?:[01]\d|2[0-3]):[0-5]\d)$/.test(value)||!Number.isFinite(Date.parse(value)))return '';
 const day=new Date(value.slice(0,10)+'T00:00:00Z');if(!Number.isFinite(day.getTime())||day.toISOString().slice(0,10)!==value.slice(0,10))return '';return new Date(value).toISOString();
};
type Context=Awaited<ReturnType<typeof requireTenant>>;
type Entry=typeof callListEntries.$inferSelect;
type State=typeof outboundLeadState.$inferSelect;
async function orgFor(ctx:Context){const [org]=await getDb().select().from(organizations).where(eq(organizations.id,ctx.organizationId)).limit(1);if(!org)throw new AccessError(404,'Bedriften finnes ikke.');return org;}
async function activeSetup(ctx:Context){const org=await orgFor(ctx);if(!org.outboundEnabled)throw new AccessError(403,'Outbound er ikke aktivert for bedriften.');if(!manager(ctx.role))await requireModuleAccess(ctx.organizationId,ctx.membershipId,'ringelister');return org;}
function readSettings(org:Awaited<ReturnType<typeof orgFor>>){const marketRules=normalizeOutboundRules(org.outboundMarketRules);return {enabled:org.outboundEnabled,currency:org.outboundCurrency,timezone:org.outboundTimezone,commissionBps:org.outboundCommissionBps,commissionMonths:org.outboundCommissionMonths,pitch:org.outboundPitch,country:org.homeCountry,organizationName:org.name,playbooks:parsePlaybooks(org.outboundPlaybooks),marketRules,contactRules:marketRules};}
// Subqueries keep large duplicate imports below D1's bind-parameter limit.
function copies(ctx:Context,entry:Entry){const number=normalizeRegistryId(entry.orgNumber,entry.country);return getDb().select({id:callListEntries.id}).from(callListEntries).where(and(eq(callListEntries.organizationId,ctx.organizationId),number?eq(callListEntries.country,entry.country):undefined,number?eq(outboundRegistryExpression(callListEntries.orgNumber,callListEntries.country),number):eq(callListEntries.id,entry.id)));}
async function entryFor(ctx:Context,entryId:unknown){if(!integer(entryId,1))throw new AccessError(400,'Velg en gyldig bedrift.');const [entry]=await getDb().select().from(callListEntries).where(and(eq(callListEntries.organizationId,ctx.organizationId),eq(callListEntries.id,Number(entryId)))).limit(1);if(!entry||!entry.listId)throw new AccessError(404,'Bedriften finnes ikke i en tilgjengelig ringeliste.');await requireList(ctx,entry.listId);return entry;}
async function stateFor(ctx:Context,entry:Entry){return (await getDb().select().from(outboundLeadState).where(and(eq(outboundLeadState.organizationId,ctx.organizationId),inArray(outboundLeadState.entryId,copies(ctx,entry)))).orderBy(desc(outboundLeadState.updatedAt),asc(outboundLeadState.id)).limit(1))[0];}
// Cheap SQL exclusions narrow the candidate set; JavaScript eligibility is
// authoritative for accent folding and recipient contact hours.
const comparableSql=(value:SQLWrapper)=>sql`lower(${value})`;
const comparableTerm=(value:string)=>value.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('en').replace(/\s+/g,' ').trim();
function visibleListScope(ctx:Context,column:SQLWrapper,listId:string|null){
 if(listId)return eq(column,Number(listId));if(manager(ctx.role))return sql`${column} is not null`;
 return inArray(column as typeof callListEntries.listId,getDb().select({id:savedCallLists.id}).from(savedCallLists).where(and(eq(savedCallLists.organizationId,ctx.organizationId),or(eq(savedCallLists.createdByMembershipId,ctx.membershipId),eq(savedCallLists.createdByMembershipId,0),inArray(savedCallLists.id,getDb().select({id:callListAssignments.listId}).from(callListAssignments).where(and(eq(callListAssignments.organizationId,ctx.organizationId),eq(callListAssignments.membershipId,ctx.membershipId))))))));
}
async function companyOwner(ctx:Context,entry:Entry){const number=normalizeRegistryId(entry.orgNumber,entry.country);if(!number)return undefined;return (await getDb().select().from(outboundCompanyOwnership).where(and(eq(outboundCompanyOwnership.organizationId,ctx.organizationId),eq(outboundCompanyOwnership.country,entry.country),eq(outboundCompanyOwnership.orgNumber,number))).limit(1))[0];}
async function checkOwner(ctx:Context,entry:Entry,adminRead=false){const [owner,state]=await Promise.all([companyOwner(ctx,entry),stateFor(ctx,entry)]),memberId=owner?.assignedMembershipId??state?.assignedMembershipId??0;if(!(adminRead&&manager(ctx.role))&&memberId!==ctx.membershipId)throw new AccessError(403,memberId?'Dette leadet tilhører en annen selger.':'Administratoren må tildele deg dette leadet først.');return {owner,state,memberId};}
async function ensureOwner(ctx:Context,entry:Entry,requestedMemberId:number,canTransfer:boolean){
 const db=getDb(),now=new Date().toISOString(),number=normalizeRegistryId(entry.orgNumber,entry.country);let state=await stateFor(ctx,entry),owner=await companyOwner(ctx,entry);const current=owner?.assignedMembershipId??state?.assignedMembershipId??0;
 if(current&&current!==requestedMemberId&&!canTransfer)throw new AccessError(403,'Bedriften er allerede tildelt en annen selger i en ringeliste.');
 if(!current&&!manager(ctx.role)&&!canTransfer)throw new AccessError(403,'Administratoren må tildele deg dette leadet først.');
 if(number){const key=and(eq(outboundCompanyOwnership.organizationId,ctx.organizationId),eq(outboundCompanyOwnership.country,entry.country),eq(outboundCompanyOwnership.orgNumber,number));await db.insert(outboundCompanyOwnership).values({organizationId:ctx.organizationId,country:entry.country,orgNumber:number,assignedMembershipId:current||requestedMemberId,updatedAt:now}).onConflictDoNothing();owner=await companyOwner(ctx,entry);if(owner?.assignedMembershipId!==requestedMemberId){if(!canTransfer)throw new AccessError(403,'Bedriften er allerede tildelt en annen selger i en ringeliste.');await db.update(outboundCompanyOwnership).set({assignedMembershipId:requestedMemberId,leaseToken:'',leaseUntil:'',updatedAt:now}).where(key);}}
 if(!state){await db.insert(outboundLeadState).values({organizationId:ctx.organizationId,entryId:entry.id,assignedMembershipId:requestedMemberId,createdAt:now,updatedAt:now}).onConflictDoNothing();state=await stateFor(ctx,entry);}
 if(!state)throw new AccessError(500,'Kunne ikke hente salgsoppfølgingen.');
 if(state.assignedMembershipId!==requestedMemberId){if(state.assignedMembershipId&&!canTransfer)throw new AccessError(403,'Dette leadet er tildelt en annen selger.');await db.update(outboundLeadState).set({assignedMembershipId:requestedMemberId,leaseToken:'',leaseUntil:'',updatedAt:now}).where(and(eq(outboundLeadState.organizationId,ctx.organizationId),inArray(outboundLeadState.entryId,copies(ctx,entry))));}
 return {...state,assignedMembershipId:requestedMemberId};
}
async function suppressionFor(ctx:Context,entry:Entry){const number=normalizeRegistryId(entry.orgNumber,entry.country);if(!number)return undefined;return (await getDb().select().from(outboundSuppression).where(and(eq(outboundSuppression.organizationId,ctx.organizationId),eq(outboundSuppression.country,entry.country),eq(outboundSuppression.orgNumber,number))).limit(1))[0];}
async function contactAllowed(ctx:Context,entry:Entry,org:Awaited<ReturnType<typeof orgFor>>,state?:State){const suppressed=!!await suppressionFor(ctx,entry);if(state&&['Kunde','Tapt'].includes(state.pipeline))throw new AccessError(409,'Åpne prospektet igjen før du ringer på nytt.');const eligibility=eligibleForOutbound({...entry,state,contactPermission:state?.contactPermission,suppressed},normalizeOutboundRules(org.outboundMarketRules),new Date());if(!eligibility.eligible)throw new AccessError(409,eligibility.reason||'Denne bedriften kan ikke kontaktes.');}
function leaseStorage(ctx:Context,entry:Entry,state:State){const number=normalizeRegistryId(entry.orgNumber,entry.country);return number?{table:outboundCompanyOwnership,key:and(eq(outboundCompanyOwnership.organizationId,ctx.organizationId),eq(outboundCompanyOwnership.country,entry.country),eq(outboundCompanyOwnership.orgNumber,number))!}:{table:outboundLeadState,key:and(eq(outboundLeadState.organizationId,ctx.organizationId),eq(outboundLeadState.id,state.id))!};}
async function dealFor(ctx:Context,entry:Entry){return (await getDb().select().from(outboundDeals).where(and(eq(outboundDeals.organizationId,ctx.organizationId),inArray(outboundDeals.entryId,copies(ctx,entry)))).orderBy(asc(outboundDeals.id)).limit(1))[0];}
async function callFingerprint(entry:Entry,body:Record<string,unknown>){
 const nextCallAt=body.nextCallAt?isoDate(body.nextCallAt):'';if(body.nextCallAt&&!nextCallAt)throw new AccessError(400,'Ugyldig dato for neste samtale.');
 const payload=JSON.stringify({entryId:entry.id,country:entry.country,orgNumber:normalizeRegistryId(entry.orgNumber,entry.country),outcome:clean(body.outcome,64),note:clean(body.note,1500),nextCallAt,contactName:clean(body.contactName,120),contactPhone:clean(body.contactPhone,40)});
 const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(payload));return [...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('');
}
async function callResult(ctx:Context,entry:Entry,requestId:string,requestFingerprint:string){const [log]=await getDb().select().from(outboundCallLogs).where(and(eq(outboundCallLogs.organizationId,ctx.organizationId),eq(outboundCallLogs.requestId,requestId))).limit(1);if(!log)return null;const matching=await getDb().select({id:callListEntries.id}).from(callListEntries).where(and(inArray(callListEntries.id,copies(ctx,entry)),eq(callListEntries.id,log.entryId))).limit(1);if(log.membershipId!==ctx.membershipId||!matching.length||(log.requestFingerprint&&log.requestFingerprint!==requestFingerprint))throw new AccessError(409,'Denne samtalereferansen tilhører en annen registrering.');const state=await stateFor(ctx,entry);return {lead:state?{...state,leaseToken:''}:null,call:log,duplicate:true};}

export async function GET(request:Request){try{
 const ctx=await requireTenant(request),db=getDb(),org=await orgFor(ctx),isManager=manager(ctx.role),settings=readSettings(org),common={settings,canManage:isManager,actorMembershipId:ctx.membershipId};
 if(!org.outboundEnabled)return json({...common,rows:[],metrics:null,deals:[],payments:[],members:[],hasMore:false});if(!isManager)await requireModuleAccess(ctx.organizationId,ctx.membershipId,'ringelister');
 const url=new URL(request.url),listId=url.searchParams.get('listId'),offset=Number(url.searchParams.get('offset')??0),entryId=url.searchParams.get('entryId');if(!integer(offset,0,100000))throw new AccessError(400,'Ugyldig side.');
 if(entryId){const entry=await entryFor(ctx,Number(entryId));await checkOwner(ctx,entry,true);const historyOffset=Number(url.searchParams.get('historyOffset')??0);if(!integer(historyOffset,0,100000))throw new AccessError(400,'Ugyldig side.');const history=await db.select({id:outboundCallLogs.id,entryId:outboundCallLogs.entryId,membershipId:outboundCallLogs.membershipId,name:memberships.name,outcome:outboundCallLogs.outcome,note:outboundCallLogs.note,nextCallAt:outboundCallLogs.nextCallAt,createdAt:outboundCallLogs.createdAt}).from(outboundCallLogs).leftJoin(memberships,and(eq(memberships.id,outboundCallLogs.membershipId),eq(memberships.organizationId,ctx.organizationId))).where(and(eq(outboundCallLogs.organizationId,ctx.organizationId),inArray(outboundCallLogs.entryId,copies(ctx,entry)))).orderBy(desc(outboundCallLogs.createdAt),desc(outboundCallLogs.id)).limit(151).offset(historyOffset);return json({...common,history:history.slice(0,150),historyHasMore:history.length>150,historyNextOffset:historyOffset+Math.min(history.length,150)});}
 const lists=await accessibleLists(ctx),allowed=lists.map(l=>l.id);if(listId)await requireList(ctx,listId);const scope=visibleListScope(ctx,callListEntries.listId,listId);
 const copy=alias(callListEntries,'outbound_copy'),stateCopy=alias(outboundLeadState,'outbound_state_copy'),identity=outboundRegistryExpression(callListEntries.orgNumber,callListEntries.country),copyIdentity=outboundRegistryExpression(copy.orgNumber,copy.country);
 const sameCompany=and(eq(copy.organizationId,ctx.organizationId),eq(copy.country,callListEntries.country),eq(copyIdentity,identity));
 const canonicalCopyIds=db.select({id:copy.id}).from(copy).where(sameCompany);
 const stateEntryQuery=db.select({entryId:stateCopy.entryId}).from(stateCopy).where(and(eq(stateCopy.organizationId,ctx.organizationId),inArray(stateCopy.entryId,canonicalCopyIds))).orderBy(desc(stateCopy.updatedAt),asc(stateCopy.id)).limit(1);
 const latestStateEntry=sql<number>`case when ${identity} = '' then ${callListEntries.id} else (${stateEntryQuery}) end`;
 const firstCopyQuery=db.select({id:copy.id}).from(copy).where(and(sameCompany,visibleListScope(ctx,copy.listId,listId))).orderBy(asc(copy.id)).limit(1);
 const firstVisibleCopy=sql<number>`case when ${identity} = '' then ${callListEntries.id} else (${firstCopyQuery}) end`;
 const now=new Date().toISOString(),queue=url.searchParams.get('queue')??'all';if(!['all','due','fresh','ready'].includes(queue))throw new AccessError(400,'Ugyldig ringekø.');
 const open=and(isNull(outboundSuppression.id),or(isNull(outboundLeadState.doNotContact),eq(outboundLeadState.doNotContact,false)),or(isNull(outboundLeadState.pipeline),inArray(outboundLeadState.pipeline,['Prospekt','Demo booket','Demo gjennomført','Prøveperiode','Tilbud'])));
 const rules=normalizeOutboundRules(org.outboundMarketRules);
 const blockedNow=homeCountries.filter(country=>!eligibleForOutbound({country,contactPermission:true}, {...rules,blockedIndustries:[],blockedRegions:[],requireContactPermission:false},now).eligible);
 const safeCountries=sql`not exists(select 1 from json_each(${JSON.stringify(blockedNow)}) where value = ${callListEntries.country})`;
 const safeIndustries=rules.blockedIndustries.length?sql`not exists(select 1 from json_each(${JSON.stringify(rules.blockedIndustries.map(comparableTerm))}) where instr(${comparableSql(callListEntries.industry)},value)>0)`:sql`1`;
 const safeRegions=rules.blockedRegions.length?sql`not exists(select 1 from json_each(${JSON.stringify(rules.blockedRegions.map(comparableTerm))}) where instr(${comparableSql(sql`${callListEntries.city} || ' ' || ${callListEntries.address}`)},value)>0)`:sql`1`;
 const ready=and(open,safeCountries,safeIndustries,safeRegions,rules.requireContactPermission?eq(outboundLeadState.contactPermission,true):undefined,
 or(isNull(outboundLeadState.pipeline),eq(outboundLeadState.pipeline,'Prospekt'),ne(outboundLeadState.nextCallAt,'')),
 or(isNull(outboundLeadState.lastOutcome),ne(outboundLeadState.lastOutcome,'Feil nummer'),ne(outboundLeadState.nextCallAt,'')));
 const rowQuery=db.select({entry:callListEntries,state:outboundLeadState,companyOwner:outboundCompanyOwnership,suppressionId:outboundSuppression.id}).from(callListEntries)
 .leftJoin(outboundLeadState,and(eq(outboundLeadState.entryId,latestStateEntry),eq(outboundLeadState.organizationId,ctx.organizationId)))
 .leftJoin(outboundCompanyOwnership,and(eq(outboundCompanyOwnership.organizationId,ctx.organizationId),eq(outboundCompanyOwnership.country,callListEntries.country),eq(outboundCompanyOwnership.orgNumber,identity)))
 .leftJoin(outboundSuppression,and(eq(outboundSuppression.organizationId,ctx.organizationId),eq(outboundSuppression.country,callListEntries.country),eq(outboundSuppression.orgNumber,identity)))
 .where(and(eq(callListEntries.organizationId,ctx.organizationId),scope,eq(callListEntries.id,firstVisibleCopy),isManager?undefined:eq(sql`coalesce(${outboundCompanyOwnership.assignedMembershipId},${outboundLeadState.assignedMembershipId},0)`,ctx.membershipId),queue==='all'?undefined:and(open,safeCountries,safeIndustries,safeRegions,rules.requireContactPermission?eq(outboundLeadState.contactPermission,true):undefined),queue==='due'?and(ne(outboundLeadState.nextCallAt,''),lte(outboundLeadState.nextCallAt,now)):undefined,queue==='ready'?or(and(ne(outboundLeadState.nextCallAt,''),lte(outboundLeadState.nextCallAt,now)),and(or(isNull(outboundLeadState.nextCallAt),eq(outboundLeadState.nextCallAt,'')),or(isNull(outboundLeadState.pipeline),eq(outboundLeadState.pipeline,'Prospekt')),or(isNull(outboundLeadState.lastOutcome),ne(outboundLeadState.lastOutcome,'Feil nummer')))):undefined,queue==='fresh'?and(or(isNull(outboundLeadState.nextCallAt),eq(outboundLeadState.nextCallAt,'')),or(isNull(outboundLeadState.pipeline),eq(outboundLeadState.pipeline,'Prospekt')),or(isNull(outboundLeadState.lastOutcome),ne(outboundLeadState.lastOutcome,'Feil nummer'))):undefined))
 .orderBy(sql`case when ${ready} then 0 else 1 end`,sql`case when ${outboundLeadState.nextCallAt} <> '' and ${outboundLeadState.nextCallAt} <= ${now} then 0 when coalesce(${outboundLeadState.nextCallAt},'') = '' then 1 else 2 end`,asc(outboundLeadState.nextCallAt),desc(callListEntries.id)).$dynamic();
 let rows=await rowQuery.limit(queue==='all'?151:201).offset(offset),nextRowOffset=offset+Math.min(rows.length,150),rowHasMore=rows.length>150;
 if(queue!=='all'){
  const chosen:typeof rows=[];let cursor=offset,scanned=0,page=rows,finished=false;rowHasMore=false;
  while(!finished){
   const take=Math.min(200,1500-scanned),candidates=page.slice(0,take);
   for(const row of candidates){
    const suppressed=!!row.state?.doNotContact||!!row.suppressionId;
    const eligible=eligibleForOutbound({...row.entry,state:row.state,contactPermission:row.state?.contactPermission,suppressed},rules,now);
    if(eligible.eligible){if(chosen.length===150){rowHasMore=true;finished=true;break;}chosen.push(row);}
    cursor++;scanned++;
   }
   if(finished)break;
   if(page.length<=take){finished=true;break;}
   if(scanned>=1500){rowHasMore=true;finished=true;break;}
   page=await rowQuery.limit(Math.min(200,1500-scanned)+1).offset(cursor);
  }
  rows=chosen;nextRowOffset=cursor;
 }
 const allUsers=await db.select({id:memberships.id,name:memberships.name,role:memberships.role,active:memberships.active,scheduledDisableAt:memberships.scheduledDisableAt}).from(memberships).where(eq(memberships.organizationId,ctx.organizationId));
 const licensed=await db.select({id:moduleLicenses.membershipId}).from(moduleLicenses).where(and(eq(moduleLicenses.organizationId,ctx.organizationId),eq(moduleLicenses.moduleKey,'ringelister'),eq(moduleLicenses.active,true)));
 const users=allUsers.map(u=>({...u,canCall:u.active&&(!u.scheduledDisableAt||u.scheduledDisableAt>now)&&(manager(u.role)||licensed.some(l=>l.id===u.id))}));
 const visible=rows.slice(0,150).map(r=>{const state=r.state?{...r.state,leaseToken:''}:null,suppressed=!!r.state?.doNotContact||!!r.suppressionId;return {...r.entry,state,assignedMembershipId:r.companyOwner?.assignedMembershipId??r.state?.assignedMembershipId??0,suppressed,lockedUntil:r.companyOwner?.leaseUntil||r.state?.leaseUntil||'',eligibility:eligibleForOutbound({...r.entry,state,contactPermission:state?.contactPermission,suppressed},rules,now)};});
 const weekAgo=new Date(Date.now()-7*86400000).toISOString(),callScope=and(eq(outboundCallLogs.organizationId,ctx.organizationId),gte(outboundCallLogs.createdAt,weekAgo),inArray(outboundCallLogs.outcome,[...outcomes]),isManager?undefined:eq(outboundCallLogs.membershipId,ctx.membershipId));
 const calls=await db.select({outcome:outboundCallLogs.outcome,membershipId:outboundCallLogs.membershipId,total:sql<number>`count(*)`}).from(outboundCallLogs).where(callScope).groupBy(outboundCallLogs.membershipId,outboundCallLogs.outcome);
 const sumCalls=(data:typeof calls)=>data.reduce((sum,c)=>sum+Number(c.total),0),attempts=sumCalls(calls),conversations=sumCalls(calls.filter(c=>conversationOutcomes.includes(c.outcome))),meetings=sumCalls(calls.filter(c=>c.outcome==='Møte booket'));
 const [{uniqueCalled}]=await db.select({uniqueCalled:sql<number>`count(distinct ${outboundCallLogs.entryId})`}).from(outboundCallLogs).where(callScope);
 const dealScope=and(eq(outboundDeals.organizationId,ctx.organizationId),isManager?undefined:eq(outboundDeals.membershipId,ctx.membershipId)),paymentScope=and(eq(outboundDealPayments.organizationId,ctx.organizationId),isManager?undefined:eq(outboundDealPayments.membershipId,ctx.membershipId));
 const deals=await db.select().from(outboundDeals).where(dealScope).orderBy(desc(outboundDeals.updatedAt)).limit(400),payments=await db.select().from(outboundDealPayments).where(paymentScope).orderBy(desc(outboundDealPayments.createdAt)).limit(400);
 const dealCounts=await db.select({membershipId:outboundDeals.membershipId,pipeline:outboundDeals.pipeline,total:sql<number>`count(*)`}).from(outboundDeals).where(dealScope).groupBy(outboundDeals.membershipId,outboundDeals.pipeline);
 const paymentTotals=await db.select({membershipId:outboundDealPayments.membershipId,currency:outboundDealPayments.currency,paidMinor:sql<number>`coalesce(sum(${outboundDealPayments.paidAmountMinor}),0)`,commissionMinor:sql<number>`coalesce(sum(${outboundDealPayments.commissionAmountMinor}),0)`}).from(outboundDealPayments).where(paymentScope).groupBy(outboundDealPayments.membershipId,outboundDealPayments.currency);
 const milestones=await db.select({membershipId:outboundDeals.membershipId,demos:sql<number>`sum(case when ${outboundDeals.demoAttendedAt} <> '' then 1 else 0 end)`,trials:sql<number>`sum(case when ${outboundDeals.trialActivatedAt} <> '' then 1 else 0 end)`}).from(outboundDeals).where(dealScope).groupBy(outboundDeals.membershipId);
 const milestoneTotals={demos:milestones.reduce((sum,m)=>sum+Number(m.demos??0),0),trials:milestones.reduce((sum,m)=>sum+Number(m.trials??0),0)};
 const paidCustomers=await db.select({id:outboundDealPayments.entryId,membershipId:outboundDealPayments.membershipId}).from(outboundDealPayments).where(paymentScope).groupBy(outboundDealPayments.entryId,outboundDealPayments.membershipId).having(sql`sum(${outboundDealPayments.paidAmountMinor})>0`);
 const customers=await db.select({id:companies.id,name:companies.name}).from(companies).where(and(eq(companies.organizationId,ctx.organizationId),await outboundCompanyScope(ctx))).orderBy(asc(companies.name)).limit(400);
 const countStage=(stage:string)=>dealCounts.filter(d=>d.pipeline===stage).reduce((sum,d)=>sum+Number(d.total),0),metrics={attempts,uniqueCalled:Number(uniqueCalled),conversations,meetings,meetingRate:conversations?Math.round(meetings/conversations*1000)/10:0,conversationRate:attempts?Math.round(conversations/attempts*1000)/10:0,weekly:true,demosAttended:milestoneTotals.demos,attendedDemos:milestoneTotals.demos,trialsActivated:milestoneTotals.trials,trials:milestoneTotals.trials,payingCustomers:paidCustomers.length,stages:Object.fromEntries(stages.map(stage=>[stage,countStage(stage)]))};
 const byMember=users.filter(u=>isManager||u.id===ctx.membershipId).map(u=>{const mine=calls.filter(c=>c.membershipId===u.id),ownDeals=dealCounts.filter(d=>d.membershipId===u.id),ownPayments=paymentTotals.filter(p=>p.membershipId===u.id),talks=sumCalls(mine.filter(c=>conversationOutcomes.includes(c.outcome))),booked=sumCalls(mine.filter(c=>c.outcome==='Møte booket'));return {membershipId:u.id,name:u.name,attempts:sumCalls(mine),conversations:talks,meetings:booked,demosAttended:Number(milestones.find(m=>m.membershipId===u.id)?.demos??0),trialsActivated:Number(milestones.find(m=>m.membershipId===u.id)?.trials??0),attendedDemos:Number(milestones.find(m=>m.membershipId===u.id)?.demos??0),trials:Number(milestones.find(m=>m.membershipId===u.id)?.trials??0),payingCustomers:paidCustomers.filter(p=>p.membershipId===u.id).length,meetingRate:talks?Math.round(booked/talks*1000)/10:0,won:ownDeals.filter(d=>d.pipeline==='Kunde').reduce((sum,d)=>sum+Number(d.total),0),commissionsByCurrency:Object.fromEntries(ownPayments.map(p=>[p.currency,Number(p.commissionMinor)]))};});
 return json({...common,rows:visible,members:isManager?users:users.filter(u=>u.id===ctx.membershipId),metrics,deals,payments,paymentTotals,byMember,customers,hasMore:rowHasMore,nextOffset:nextRowOffset,listId,listCount:lists.length});
}catch(error){return accessResponse(error);}}

function parsePlaybooks(value:unknown){
 let books:unknown=value;if(typeof value==='string'){try{books=JSON.parse(value);}catch{throw new AccessError(400,'Ugyldig salgsbibliotek.');}}
 if(!books||typeof books!=='object'||Array.isArray(books))throw new AccessError(400,'Ugyldig salgsbibliotek.');
 const rows=Object.entries(books);if(rows.length>249)throw new AccessError(400,'For mange land i salgsbiblioteket.');
 const result:Record<string,Record<string,string>>={};
 for(const [country,content] of rows){if(!/^[A-Z]{2}$/.test(country)||!content||typeof content!=='object'||Array.isArray(content))throw new AccessError(400,'Velg gyldige land og tekster.');const fields:Record<string,string>={};for(const field of ['phoneScript','emailSubject','emailBody','productInfo']){const text=(content as Record<string,unknown>)[field]??'';if(typeof text!=='string'||text.length>8000)throw new AccessError(400,'Salgsbibliotekets tekster kan være maks 8 000 tegn hver.');fields[field]=text.trim();}result[country]=fields;}
 if(JSON.stringify(result).length>80000)throw new AccessError(400,'Salgsbiblioteket er for stort.');return result;
}
export async function POST(request:Request){try{
 const ctx=await requireTenant(request),db=getDb(),raw=await request.json().catch(()=>{throw new AccessError(400,'Ugyldig JSON.');});if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new AccessError(400,'Ugyldig handling.');const body=raw as Record<string,unknown>,now=new Date().toISOString(),type=String(body.type??'');
 if(type==='settings'){
  if(!manager(ctx.role))throw new AccessError(403,'Bare administrator kan endre outbound-innstillinger.');const org=await orgFor(ctx);
  if(typeof body.enabled!=='boolean'||typeof body.currency!=='string'||!/^[A-Z]{3}$/.test(body.currency))throw new AccessError(400,'Ugyldig innstilling.');
  let policy,rules;try{policy=validateCommissionPolicy(body.commissionBps,body.commissionMonths??org.outboundCommissionMonths);rules=normalizeOutboundRules(body.marketRules??body.contactRules??org.outboundMarketRules);}catch(e){throw new AccessError(400,e instanceof Error?e.message:'Ugyldige innstillinger.');}
  const timezone=clean(body.timezone,64),pitch=clean(body.pitch,8000),playbooks=parsePlaybooks(body.playbooks??org.outboundPlaybooks);
  try{new Intl.DateTimeFormat('en',{timeZone:timezone}).format(new Date());new Intl.NumberFormat('en',{style:'currency',currency:body.currency}).format(0);}catch{throw new AccessError(400,'Velg en gyldig valuta og tidssone.');}
  const [saved]=await db.update(organizations).set({outboundEnabled:body.enabled,outboundCurrency:body.currency,outboundTimezone:timezone,outboundCommissionBps:policy.commissionBps,outboundCommissionMonths:policy.commissionMonths,outboundPitch:pitch,outboundMarketRules:JSON.stringify(rules),outboundPlaybooks:JSON.stringify(playbooks)}).where(eq(organizations.id,ctx.organizationId)).returning();return json({settings:readSettings(saved)});
 }
 const org=await activeSetup(ctx),isManager=manager(ctx.role);
 if(type==='assign')return await assignLeads(ctx,body,now);
 if(type==='refund')return await refundPayment(ctx,body,now);
 const entry=await entryFor(ctx,body.entryId);
 if(type==='acquire'){
  const state=await ensureOwner(ctx,entry,ctx.membershipId,false);await contactAllowed(ctx,entry,org,state);
  const lease=leaseStorage(ctx,entry,state),token=clean(body.leaseToken,100),leaseToken=token&&/^[a-zA-Z0-9_-]{20,100}$/.test(token)?token:crypto.randomUUID(),expiresAt=new Date(Date.now()+120000).toISOString();
  const saved=await db.update(lease.table).set({leaseToken,leaseUntil:expiresAt}).where(and(lease.key,eq(lease.table.assignedMembershipId,ctx.membershipId),or(eq(lease.table.leaseToken,''),lte(lease.table.leaseUntil,now),eq(lease.table.leaseToken,leaseToken)))).returning({id:lease.table.id});
  if(!saved.length)throw new AccessError(409,'Bedriften er åpen i en annen ringeøkt. Velg neste bedrift eller vent i to minutter.');return json({leaseToken,expiresAt,membershipId:ctx.membershipId});
 }
 if(type==='release'){
  const {state}=await checkOwner(ctx,entry);if(!state)return json({ok:true});const token=clean(body.leaseToken,100),lease=leaseStorage(ctx,entry,state);if(!token)throw new AccessError(400,'Ringeøkten mangler referanse.');const released=await db.update(lease.table).set({leaseToken:'',leaseUntil:''}).where(and(lease.key,eq(lease.table.assignedMembershipId,ctx.membershipId),eq(lease.table.leaseToken,token))).returning({id:lease.table.id});if(!released.length)throw new AccessError(409,'Ringeøkten har en annen referanse.');return json({ok:true});
 }
 if(type==='dial')return await logCall(ctx,entry,org,body,now);
 if(type==='permission'){
  await checkOwner(ctx,entry,true);if(typeof body.permission!=='boolean')throw new AccessError(400,'Bekreft om kontakt er tillatt.');
  const current=await stateFor(ctx,entry),owner=(await companyOwner(ctx,entry))?.assignedMembershipId??current?.assignedMembershipId??ctx.membershipId,state=await ensureOwner(ctx,entry,owner,isManager);
  if(state.doNotContact||await suppressionFor(ctx,entry))throw new AccessError(409,'Kontaktreservasjon kan ikke fjernes ved å bekrefte kontaktgrunnlag.');
  const note=clean(body.note,500);if(body.permission&&!note)throw new AccessError(400,'Dokumenter grunnlaget for at kontakt er tillatt.');
  await db.batch([db.update(outboundLeadState).set({contactPermission:body.permission,lastNote:note||state.lastNote,updatedAt:now}).where(and(eq(outboundLeadState.organizationId,ctx.organizationId),inArray(outboundLeadState.entryId,copies(ctx,entry)))),db.insert(outboundCallLogs).values({organizationId:ctx.organizationId,entryId:entry.id,membershipId:ctx.membershipId,outcome:body.permission?'Kontaktgrunnlag bekreftet':'Kontaktgrunnlag fjernet',note,createdAt:now})]);return json({ok:true});
 }
 if(type==='callback'){
  await checkOwner(ctx,entry,true);const current=await stateFor(ctx,entry),owner=(await companyOwner(ctx,entry))?.assignedMembershipId??current?.assignedMembershipId??ctx.membershipId,state=await ensureOwner(ctx,entry,owner,isManager);
  if(state.doNotContact||await suppressionFor(ctx,entry))throw new AccessError(409,'Reserverte bedrifter kan ikke følges opp.');if(['Kunde','Tapt'].includes(state.pipeline))throw new AccessError(409,'Åpne prospektet igjen før du planlegger en ny samtale.');const nextCallAt=isoDate(body.nextCallAt);if(!nextCallAt)throw new AccessError(400,'Oppgi en gyldig dato for neste samtale.');await db.update(outboundLeadState).set({nextCallAt,updatedAt:now}).where(and(eq(outboundLeadState.organizationId,ctx.organizationId),inArray(outboundLeadState.entryId,copies(ctx,entry))));return json({lead:{...state,nextCallAt,leaseToken:''}});
 }
 if(type==='stage')return await saveStage(ctx,entry,org,body,now);
 if(type==='payment')return await recordPayment(ctx,entry,org,body,now);
 throw new AccessError(400,'Ukjent outbound-handling.');
}catch(error){return accessResponse(error);}}

async function assignLeads(ctx:Context,body:Record<string,unknown>,now:string){
 if(!manager(ctx.role))throw new AccessError(403,'Bare administrator kan fordele leads.');const db=getDb(),rawMembers=Array.isArray(body.membershipIds)?body.membershipIds:[body.membershipId];
 if(!rawMembers.length||rawMembers.length>30||rawMembers.some(id=>!integer(id,1)))throw new AccessError(400,'Velg minst én aktiv selger.');const memberIds=[...new Set(rawMembers.map(Number))];
 const members=await db.select().from(memberships).where(and(eq(memberships.organizationId,ctx.organizationId),inArray(memberships.id,memberIds),eq(memberships.active,true),or(eq(memberships.scheduledDisableAt,''),gt(memberships.scheduledDisableAt,now))));if(members.length!==memberIds.length)throw new AccessError(400,'Alle selgere må være aktive i denne bedriften.');
 const licenses=await db.select().from(moduleLicenses).where(and(eq(moduleLicenses.organizationId,ctx.organizationId),inArray(moduleLicenses.membershipId,memberIds),eq(moduleLicenses.moduleKey,'ringelister'),eq(moduleLicenses.active,true)));if(members.some(m=>!manager(m.role)&&!licenses.some(l=>l.membershipId===m.id)))throw new AccessError(400,'Selgeren mangler lisens til Ringelister.');
 let entries:Entry[];
 if(Array.isArray(body.entryIds)){if(!body.entryIds.length||body.entryIds.length>50||body.entryIds.some(id=>!integer(id,1)))throw new AccessError(400,'Velg 1–50 gyldige bedrifter.');entries=[];for(const id of [...new Set(body.entryIds.map(Number))])entries.push(await entryFor(ctx,id));}
 else{
  const count=Number(body.count??50),mode=body.mode??'unassigned';if(!integer(count,1,150)||!['unassigned','all'].includes(String(mode)))throw new AccessError(400,'Velg 1–150 bedrifter og en gyldig fordeling.');if(body.listId!=null)await requireList(ctx,body.listId);
  const identity=outboundRegistryExpression(callListEntries.orgNumber,callListEntries.country),copy=alias(callListEntries,'distribution_copy'),stateCopy=alias(outboundLeadState,'distribution_state_copy');
  const sameCompany=and(eq(copy.organizationId,ctx.organizationId),or(eq(copy.id,callListEntries.id),and(ne(identity,''),eq(copy.country,callListEntries.country),eq(outboundRegistryExpression(copy.orgNumber,copy.country),identity))));
  const first=db.select({id:copy.id}).from(copy).where(and(sameCompany,body.listId!=null?eq(copy.listId,Number(body.listId)):sql`${copy.listId} is not null`)).orderBy(asc(copy.id)).limit(1);
  const latestState=db.select({id:stateCopy.entryId}).from(stateCopy).innerJoin(copy,eq(copy.id,stateCopy.entryId)).where(and(eq(stateCopy.organizationId,ctx.organizationId),sameCompany)).orderBy(desc(stateCopy.updatedAt),asc(stateCopy.id)).limit(1);
  const candidates=await db.select({entry:callListEntries,owner:outboundCompanyOwnership.assignedMembershipId,stateOwner:outboundLeadState.assignedMembershipId}).from(callListEntries)
  .leftJoin(outboundCompanyOwnership,and(eq(outboundCompanyOwnership.organizationId,ctx.organizationId),eq(outboundCompanyOwnership.country,callListEntries.country),eq(outboundCompanyOwnership.orgNumber,identity)))
  .leftJoin(outboundLeadState,and(eq(outboundLeadState.organizationId,ctx.organizationId),eq(outboundLeadState.entryId,latestState)))
  .where(and(eq(callListEntries.organizationId,ctx.organizationId),eq(callListEntries.id,first),body.listId!=null?eq(callListEntries.listId,Number(body.listId)):sql`${callListEntries.listId} is not null`,mode==='unassigned'?eq(sql`coalesce(${outboundCompanyOwnership.assignedMembershipId},${outboundLeadState.assignedMembershipId},0)`,0):undefined)).orderBy(asc(callListEntries.id)).limit(count);
  entries=[];const seen=new Set<string>();for(const row of candidates){const key=outboundCompanyKey(row.entry);if(seen.has(key))continue;seen.add(key);entries.push(row.entry);if(entries.length===count)break;}
 }
 const unique=[...new Map(entries.map(e=>[outboundCompanyKey(e),e])).values()],statements:Parameters<ReturnType<typeof getDb>['batch']>[0][number][]=[];
 for(let i=0;i<unique.length;i++){
  const entry=unique[i],memberId=memberIds[i%memberIds.length],number=normalizeRegistryId(entry.orgNumber,entry.country);
  if(number)statements.push(db.insert(outboundCompanyOwnership).values({organizationId:ctx.organizationId,country:entry.country,orgNumber:number,assignedMembershipId:memberId,updatedAt:now}).onConflictDoUpdate({target:[outboundCompanyOwnership.organizationId,outboundCompanyOwnership.country,outboundCompanyOwnership.orgNumber],set:{assignedMembershipId:memberId,leaseToken:'',leaseUntil:'',updatedAt:now}}));
  statements.push(db.insert(outboundLeadState).values({organizationId:ctx.organizationId,entryId:entry.id,assignedMembershipId:memberId,createdAt:now,updatedAt:now}).onConflictDoNothing());
  statements.push(db.update(outboundLeadState).set({assignedMembershipId:memberId,leaseToken:'',leaseUntil:'',updatedAt:now}).where(and(eq(outboundLeadState.organizationId,ctx.organizationId),inArray(outboundLeadState.entryId,copies(ctx,entry)))));
  // Retain list delegation. All duplicate copies become visible to the same seller.
  const lists=await db.selectDistinct({id:callListEntries.listId}).from(callListEntries).where(inArray(callListEntries.id,copies(ctx,entry)));
  for(const list of lists)if(list.id)statements.push(db.insert(callListAssignments).values({organizationId:ctx.organizationId,listId:list.id,membershipId:memberId,assignedBy:ctx.user.displayName,createdAt:now,acknowledgedAt:''}).onConflictDoNothing());
 }
 if(statements.length)await db.batch(statements as [typeof statements[number],...typeof statements[number][]]);return json({assigned:unique.length,distribution:memberIds.map((id,index)=>({membershipId:id,assigned:unique.filter((_,i)=>i%memberIds.length===index).length}))});
}

function insertFields<T extends AnySQLiteTable>(table:T,values:Record<string,SQL>):{[K in keyof T['_']['columns']]:SQL.Aliased}{
 const fields:Record<string,SQL.Aliased>={};for(const [key,column] of Object.entries(getTableColumns(table))){const value=column.default;fields[key]=(values[key]??sql`${typeof value==='boolean'?Number(value):value??null}`).as(column.name);}return fields as {[K in keyof T['_']['columns']]:SQL.Aliased};
}
async function logCall(ctx:Context,entry:Entry,org:Awaited<ReturnType<typeof orgFor>>,body:Record<string,unknown>,now:string){
 await checkOwner(ctx,entry);const db=getDb(),outcome=clean(body.outcome,64),requestId=clean(body.requestId,100),token=clean(body.leaseToken,100);
 if(!outcomes.includes(outcome as typeof outcomes[number]))throw new AccessError(400,'Ugyldig samtaleresultat.');if(!/^[a-zA-Z0-9_-]{20,100}$/.test(requestId))throw new AccessError(400,'Samtalen mangler en gyldig referanse.');const requestFingerprint=await callFingerprint(entry,body),duplicate=await callResult(ctx,entry,requestId,requestFingerprint);if(duplicate)return json(duplicate);
 if(typeof body.note!=='string'||body.note.length>1500)throw new AccessError(400,'Notatet kan være maks 1 500 tegn.');if(!token)throw new AccessError(409,'Åpne bedriften i ringemodus før du registrerer samtalen.');
 const state=await ensureOwner(ctx,entry,ctx.membershipId,false),closed=outcome==='Reservert mot kontakt';if(!closed)await contactAllowed(ctx,entry,org,state);
 let nextAt=body.nextCallAt?isoDate(body.nextCallAt):'';if(body.nextCallAt&&!nextAt)throw new AccessError(400,'Ugyldig dato for neste samtale.');if(!nextAt&&['Ikke svar','Sentralbord','Interessert','Beslutningstaker kontaktet'].includes(outcome))nextAt=new Date(Date.now()+48*3600000).toISOString();if(['Reservert mot kontakt','Feil nummer','Ikke interessert'].includes(outcome))nextAt='';
 const lease=leaseStorage(ctx,entry,state),validLease=and(lease.key,eq(lease.table.assignedMembershipId,ctx.membershipId),eq(lease.table.leaseToken,token),gt(lease.table.leaseUntil,now));
 const allowedState=closed?sql`1`:sql`exists(select 1 from ${outboundLeadState} where ${outboundLeadState.id} = ${state.id} and ${outboundLeadState.organizationId} = ${ctx.organizationId} and ${outboundLeadState.doNotContact} = 0 and ${outboundLeadState.pipeline} not in ('Kunde','Tapt') ${normalizeOutboundRules(org.outboundMarketRules).requireContactPermission?sql`and ${outboundLeadState.contactPermission} = 1`:sql``})`;
 const notSuppressed=closed?sql`1`:sql`not exists(select 1 from ${outboundSuppression} where ${outboundSuppression.organizationId} = ${ctx.organizationId} and ${outboundSuppression.country} = ${entry.country} and ${outboundSuppression.orgNumber} = ${normalizeRegistryId(entry.orgNumber,entry.country)})`;
 const insertedLog=db.insert(outboundCallLogs).select(db.select(insertFields(outboundCallLogs, {requestId:sql<string>`${requestId}`,requestFingerprint:sql<string>`${requestFingerprint}`,organizationId:sql<number>`${ctx.organizationId}`,entryId:sql<number>`${entry.id}`,membershipId:sql<number>`${ctx.membershipId}`,outcome:sql<string>`${outcome}`,note:sql<string>`${clean(body.note,1500)}`,nextCallAt:sql<string>`${nextAt}`,createdAt:sql<string>`${now}`})).from(lease.table).where(and(validLease,allowedState,notSuppressed))).returning({id:outboundCallLogs.id});
 const existsLog=sql`changes() > 0 and exists (select 1 from ${outboundCallLogs} where ${outboundCallLogs.organizationId} = ${ctx.organizationId} and ${outboundCallLogs.requestId} = ${requestId} and ${outboundCallLogs.membershipId} = ${ctx.membershipId})`,pipeline=outcome==='Møte booket'?'Demo booket':closed||outcome==='Ikke interessert'?'Tapt':state.pipeline,note=clean(body.note,1500),status=closed||outcome==='Ikke interessert'?'Ikke aktuell':outcome==='Møte booket'?'Møte booket':outcome==='Ikke svar'?'Ringte – ikke svar':'Kontaktet';
 const statements:Parameters<ReturnType<typeof getDb>['batch']>[0][number][]=[insertedLog,
 db.update(outboundLeadState).set({lastOutcome:outcome,lastNote:note,nextCallAt:nextAt,attempts:sql`${outboundLeadState.attempts}+1`,doNotContact:closed||state.doNotContact,pipeline,contactName:clean(body.contactName,120)||state.contactName,contactPhone:clean(body.contactPhone,40)||state.contactPhone,updatedAt:now}).where(and(eq(outboundLeadState.organizationId,ctx.organizationId),inArray(outboundLeadState.entryId,copies(ctx,entry)),existsLog)),
 db.update(callListEntries).set({handledBy:ctx.user.displayName,updatedAt:now,status}).where(and(eq(callListEntries.organizationId,ctx.organizationId),inArray(callListEntries.id,copies(ctx,entry)),existsLog)),
 db.update(lease.table).set({leaseToken:'',leaseUntil:''}).where(and(validLease,existsLog))];
 if(outcome==='Møte booket'){
  const deal=await dealFor(ctx,entry),dealEntryId=deal?.entryId??state.entryId;
  statements.push(db.insert(outboundDeals).select(db.select(insertFields(outboundDeals, {organizationId:sql<number>`${ctx.organizationId}`,entryId:sql<number>`${dealEntryId}`,membershipId:sql<number>`${deal?.membershipId??ctx.membershipId}`,pipeline:sql<string>`'Demo booket'`,monthlyAmountMinor:sql<number>`${deal?.monthlyAmountMinor??0}`,currency:sql<string>`${deal?.currency??org.outboundCurrency}`,commissionBps:sql<number>`${deal?.commissionBps??org.outboundCommissionBps}`,commissionMonths:sql<number>`${deal?.commissionMonths??org.outboundCommissionMonths}`,note:sql<string>`${note}`,createdAt:sql<string>`${now}`,updatedAt:sql<string>`${now}`})).from(outboundLeadState).where(and(eq(outboundLeadState.id,state.id),existsLog))).onConflictDoUpdate({target:outboundDeals.entryId,set:{pipeline:'Demo booket',updatedAt:now}}));
 }
 const number=normalizeRegistryId(entry.orgNumber,entry.country);if(closed&&number)statements.push(db.insert(outboundSuppression).select(db.select(insertFields(outboundSuppression, {organizationId:sql<number>`${ctx.organizationId}`,country:sql<string>`${entry.country}`,orgNumber:sql<string>`${number}`,name:sql<string>`${entry.name}`,createdByMembershipId:sql<number>`${ctx.membershipId}`,reason:sql<string>`${clean(body.note,500)}`,createdAt:sql<string>`${now}`})).from(outboundLeadState).where(and(eq(outboundLeadState.id,state.id),existsLog))).onConflictDoNothing());
 if(closed||outcome==='Ikke interessert')statements.push(db.update(outboundDeals).set({pipeline:'Tapt',updatedAt:now}).where(and(eq(outboundDeals.organizationId,ctx.organizationId),inArray(outboundDeals.entryId,copies(ctx,entry)),existsLog)));
 try{const result=await db.batch(statements as [typeof statements[number],...typeof statements[number][]]);if(!(result[0] as unknown[]).length)throw new AccessError(409,'Ringeøkten er utløpt eller leadet er tildelt på nytt. Åpne bedriften igjen.');}
 catch(error){if(!(error instanceof AccessError)){const result=await callResult(ctx,entry,requestId,requestFingerprint);if(result)return json(result);}throw error;}
 const updated=await stateFor(ctx,entry);return json({lead:updated?{...updated,leaseToken:''}:null});
}

async function saveStage(ctx:Context,entry:Entry,org:Awaited<ReturnType<typeof orgFor>>,body:Record<string,unknown>,now:string){try{
 await checkOwner(ctx,entry,true);const db=getDb(),stage=clean(body.pipeline,40),isManager=manager(ctx.role);if(!stages.includes(stage as typeof stages[number]))throw new AccessError(400,'Ugyldig salgsfase.');
 const current=await stateFor(ctx,entry),owner=(await companyOwner(ctx,entry))?.assignedMembershipId??current?.assignedMembershipId??ctx.membershipId,state=await ensureOwner(ctx,entry,owner,isManager),suppression=await suppressionFor(ctx,entry);if((state.doNotContact||suppression)&&stage!=='Tapt')throw new AccessError(409,'Reserverte bedrifter kan ikke kontaktes.');
 const existing=await dealFor(ctx,entry),monthlyAmountMinor=Number(body.monthlyAmountMinor??existing?.monthlyAmountMinor??0);if(!integer(monthlyAmountMinor,0,10000000000))throw new AccessError(400,'Ugyldig kontraktsverdi.');
 const note=clean(body.note,1000),fields:Partial<typeof outboundDeals.$inferInsert>={};
 if(body.customerCompanyId!=null){if(!integer(body.customerCompanyId,1))throw new AccessError(400,'Velg en gyldig CRM-kunde.');const [company]=await db.select({id:companies.id,country:companies.country,orgNumber:companies.orgNumber}).from(companies).where(and(eq(companies.organizationId,ctx.organizationId),eq(companies.id,Number(body.customerCompanyId)))).limit(1);if(!company)throw new AccessError(404,'Kunden finnes ikke i denne bedriften.');await requireOutboundCompany(ctx,company.id);if(normalizeRegistryId(entry.orgNumber,entry.country)&&(company.country!==entry.country||normalizeRegistryId(company.orgNumber,company.country)!==normalizeRegistryId(entry.orgNumber,entry.country)))throw new AccessError(400,'Kunden må ha samme land og organisasjonsnummer som prospektet.');if(!isManager&&entry.customerId!==company.id&&(!normalizeRegistryId(entry.orgNumber,entry.country)||company.country!==entry.country||normalizeRegistryId(company.orgNumber,company.country)!==normalizeRegistryId(entry.orgNumber,entry.country)))throw new AccessError(403,'Kunden må være den samme bedriften som prospektet.');fields.customerCompanyId=company.id;}
 else if(!existing?.customerCompanyId){
  const number=normalizeRegistryId(entry.orgNumber,entry.country);
  const matching=await db.select({id:companies.id,country:companies.country,orgNumber:companies.orgNumber}).from(companies).where(and(eq(companies.organizationId,ctx.organizationId),entry.customerId?eq(companies.id,entry.customerId):number?and(eq(companies.country,entry.country),eq(outboundRegistryExpression(companies.orgNumber,companies.country),number)):sql`0`)).limit(2);
  if(matching.length===1){const company=matching[0];if(!number||(company.country===entry.country&&normalizeRegistryId(company.orgNumber,company.country)===number)){await requireOutboundCompany(ctx,company.id);fields.customerCompanyId=company.id;}}
 }
 // Global customer organizations are never inferred from a name or accessed by ordinary sellers.
 if(body.customerOrganizationId!=null){if(!ctx.isSuperadmin||!integer(body.customerOrganizationId,1))throw new AccessError(403,'Du kan ikke knytte andre organisasjoner til dette salget.');const [customer]=await db.select({id:organizations.id}).from(organizations).where(and(eq(organizations.id,Number(body.customerOrganizationId)),eq(organizations.homeCountry,entry.country),eq(outboundRegistryExpression(organizations.orgNumber,organizations.homeCountry),normalizeRegistryId(entry.orgNumber,entry.country)))).limit(1);if(!customer||customer.id===ctx.organizationId)throw new AccessError(404,'Kundeorganisasjonen finnes ikke.');fields.customerOrganizationId=customer.id;}
 if(body.commissionBps!=null||body.commissionMonths!=null||body.commissionAgreedAt!=null){
  if(!isManager)throw new AccessError(403,'Bare administrator kan godkjenne provisjonsavtalen.');
  const paid=existing?await db.select({id:outboundDealPayments.id}).from(outboundDealPayments).where(and(eq(outboundDealPayments.organizationId,ctx.organizationId),eq(outboundDealPayments.entryId,existing.entryId))).limit(1):[];if(paid.length)throw new AccessError(409,'Provisjonsavtalen kan ikke endres etter registrerte betalinger.');
  try{Object.assign(fields,validateCommissionPolicy(body.commissionBps??existing?.commissionBps??org.outboundCommissionBps,body.commissionMonths??existing?.commissionMonths??org.outboundCommissionMonths));}catch(e){throw new AccessError(400,e instanceof Error?e.message:'Ugyldig provisjonsavtale.');}
  if(body.commissionAgreedAt!=null){const date=isoDate(body.commissionAgreedAt);if(!date||date>now)throw new AccessError(400,'Oppgi når provisjonsavtalen ble godkjent.');fields.commissionAgreedAt=date;}
 }
 for(const key of ['subscriptionActivatedAt','subscriptionCancelledAt'] as const){if(body[key]==null)continue;if(!isManager)throw new AccessError(403,'Bare administrator kan bekrefte abonnementet.');const value=body[key]===''?'':isoDate(body[key]);if(body[key]!==''&&(!value||value>now))throw new AccessError(400,'Oppgi en gyldig abonnementsdato.');if(existing?.subscriptionActivatedAt&&key==='subscriptionActivatedAt'&&value!==existing.subscriptionActivatedAt)throw new AccessError(409,'Abonnementets opprinnelige aktiveringsdato kan ikke flyttes.');fields[key]=value;}
 if(stage==='Demo gjennomført'&&!existing?.demoAttendedAt)fields.demoAttendedAt=now;if(stage==='Prøveperiode'&&!existing?.trialActivatedAt)fields.trialActivatedAt=now;
 if(existing&&((fields.customerCompanyId!=null&&fields.customerCompanyId!==existing.customerCompanyId)||(fields.customerOrganizationId!=null&&fields.customerOrganizationId!==existing.customerOrganizationId))){const paid=await db.select({id:outboundDealPayments.id}).from(outboundDealPayments).where(and(eq(outboundDealPayments.organizationId,ctx.organizationId),eq(outboundDealPayments.entryId,existing.entryId))).limit(1);if(paid.length)throw new AccessError(409,'Kundetilknytningen kan ikke endres etter registrerte betalinger.');}
 const activated=fields.subscriptionActivatedAt??existing?.subscriptionActivatedAt??'',cancelled=fields.subscriptionCancelledAt??existing?.subscriptionCancelledAt??'';if(cancelled&&(!activated||cancelled<activated))throw new AccessError(400,'Avslutningsdatoen må være etter aktivering.');
 const nextCallAt=body.nextCallAt==null?(['Kunde','Tapt','Demo booket'].includes(stage)?'':state.nextCallAt):body.nextCallAt===''?'':isoDate(body.nextCallAt);if(body.nextCallAt&&!nextCallAt)throw new AccessError(400,'Ugyldig oppfølgingsdato.');
 const legacyStatus=stage==='Kunde'?'Lagt til som kunde':stage==='Tapt'?'Ikke aktuell':stage==='Demo booket'?'Møte booket':stage==='Tilbud'?'Tilbud sendt':stage==='Prøveperiode'||stage==='Demo gjennomført'?'Kontaktet':'Ny';
 await db.batch([
 db.update(outboundLeadState).set({pipeline:stage,nextCallAt,lastNote:note||state.lastNote,lastOutcome:stage==='Prospekt'&&state.lastOutcome==='Feil nummer'?'':state.lastOutcome,updatedAt:now}).where(and(eq(outboundLeadState.organizationId,ctx.organizationId),inArray(outboundLeadState.entryId,copies(ctx,entry)))),
 db.insert(outboundDeals).values({organizationId:ctx.organizationId,entryId:existing?.entryId??state.entryId,membershipId:existing?.membershipId??owner,pipeline:stage,monthlyAmountMinor,currency:existing?.currency??org.outboundCurrency,commissionBps:existing?.commissionBps??org.outboundCommissionBps,commissionMonths:existing?.commissionMonths??org.outboundCommissionMonths,...fields,note,createdAt:now,updatedAt:now}).onConflictDoUpdate({target:outboundDeals.entryId,set:{pipeline:stage,monthlyAmountMinor,...fields,note,updatedAt:now}}),
 db.update(callListEntries).set({status:legacyStatus,updatedAt:now}).where(and(eq(callListEntries.organizationId,ctx.organizationId),inArray(callListEntries.id,copies(ctx,entry))))]);return json({ok:true});
}catch(error){if(!(error instanceof AccessError)&&/outbound financial terms are frozen/.test(String(error instanceof Error&&'cause' in error?error.cause:error)))throw new AccessError(409,'Betalingen er registrert. Provisjonsavtalen og kundetilknytningen kan ikke endres.');throw error;}
}

async function recordPayment(ctx:Context,entry:Entry,org:Awaited<ReturnType<typeof orgFor>>,body:Record<string,unknown>,now:string){
 if(!manager(ctx.role))throw new AccessError(403,'Kun administrator kan bekrefte betalinger.');const db=getDb(),deal=await dealFor(ctx,entry);if(!deal||deal.pipeline!=='Kunde')throw new AccessError(400,'Sett salgsfasen til Kunde før betalingen registreres.');
 const ref=clean(body.reference,100),amount=Number(body.paidAmountMinor);if(ref.length<3||!integer(amount,1,10000000000)||body.confirmed!==true)throw new AccessError(400,'Bekreft en faktisk mottatt betaling, beløp og referanse.');
 let receivedAt,referenceKey,commission;try{receivedAt=validateReceivedAt(body.receivedAt);referenceKey=paymentReferenceKey(ref);commission=receivedCommission(deal,amount,receivedAt,org.outboundTimezone);}catch(e){throw new AccessError(400,e instanceof Error?e.message:'Ugyldig betaling.');}
 const eligibility=commissionEligibility(deal,receivedAt,org.outboundTimezone);if((!deal.customerCompanyId&&!deal.customerOrganizationId)||!deal.subscriptionActivatedAt)throw new AccessError(400,eligibility.reason||'Knytt salget til en kunde og bekreft aktivert abonnement først.');if(deal.commissionBps>0&&!deal.commissionAgreedAt)throw new AccessError(400,'Administrator må bekrefte provisjonsavtalen før betaling registreres.');
 const paymentValues={organizationId:sql<number>`${ctx.organizationId}`,entryId:sql<number>`${deal.entryId}`,membershipId:sql<number>`${deal.membershipId}`,paymentReference:sql<string>`${ref}`,paymentReferenceKey:sql<string>`${referenceKey}`,paidAmountMinor:sql<number>`${amount}`,currency:sql<string>`${deal.currency}`,commissionBps:sql<number>`${deal.commissionBps}`,commissionAmountMinor:sql<number>`${commission.commissionAmountMinor}`,receivedAt:sql<string>`${receivedAt}`,createdByMembershipId:sql<number>`${ctx.membershipId}`,createdAt:sql<string>`${now}`};
 const unchanged=and(eq(outboundDeals.id,deal.id),eq(outboundDeals.organizationId,ctx.organizationId),eq(outboundDeals.pipeline,'Kunde'),eq(outboundDeals.membershipId,deal.membershipId),eq(outboundDeals.currency,deal.currency),eq(outboundDeals.commissionBps,deal.commissionBps),eq(outboundDeals.commissionMonths,deal.commissionMonths),eq(outboundDeals.commissionAgreedAt,deal.commissionAgreedAt),eq(outboundDeals.subscriptionActivatedAt,deal.subscriptionActivatedAt),eq(outboundDeals.subscriptionCancelledAt,deal.subscriptionCancelledAt),deal.customerCompanyId==null?isNull(outboundDeals.customerCompanyId):eq(outboundDeals.customerCompanyId,deal.customerCompanyId),deal.customerOrganizationId==null?isNull(outboundDeals.customerOrganizationId):eq(outboundDeals.customerOrganizationId,deal.customerOrganizationId));
 const inserted=await db.insert(outboundDealPayments).select(db.select(insertFields(outboundDealPayments,paymentValues)).from(outboundDeals).where(unchanged)).onConflictDoNothing().returning({id:outboundDealPayments.id});if(!inserted.length)throw new AccessError(409,'Betalingsreferansen er allerede registrert eller avtalen er endret. Oppdater oversikten før du prøver igjen.');return json({ok:true,commissionAmountMinor:commission.commissionAmountMinor,commissionEligible:commission.eligible,commissionReason:commission.reason,warning:'Registrert etter administrativ bekreftelse; ingen automatisk betalingskontroll er utført.'});
}
async function refundPayment(ctx:Context,body:Record<string,unknown>,now:string){
 if(!manager(ctx.role))throw new AccessError(403,'Kun administrator kan bekrefte refusjoner.');if(!integer(body.paymentId,1)||body.confirmed!==true)throw new AccessError(400,'Bekreft en faktisk refusjon og velg betalingen.');
 const db=getDb(),[payment]=await db.select().from(outboundDealPayments).where(and(eq(outboundDealPayments.organizationId,ctx.organizationId),eq(outboundDealPayments.id,Number(body.paymentId)))).limit(1);if(!payment||payment.refundPaymentId)throw new AccessError(404,'Den opprinnelige betalingen finnes ikke.');const refunds=await db.select().from(outboundDealPayments).where(and(eq(outboundDealPayments.organizationId,ctx.organizationId),eq(outboundDealPayments.refundPaymentId,payment.id)));
 const amount=Number(body.refundAmountMinor),ref=clean(body.reference,100);let result,receivedAt,referenceKey;try{result=refundCommission(payment,refunds,amount);receivedAt=validateReceivedAt(body.receivedAt);referenceKey=paymentReferenceKey(ref);}catch(e){throw new AccessError(400,e instanceof Error?e.message:'Ugyldig refusjon.');}if(ref.length<3||receivedAt<payment.receivedAt)throw new AccessError(400,'Oppgi en refusjonsreferanse og dato etter betalingen.');
 // The database guard rechecks cumulative cash and commission inside the same write.
 try{const inserted=await db.insert(outboundDealPayments).values({organizationId:ctx.organizationId,entryId:payment.entryId,membershipId:payment.membershipId,paymentReference:ref,paymentReferenceKey:referenceKey,paidAmountMinor:result.paidAmountMinor,currency:payment.currency,commissionBps:payment.commissionBps,commissionAmountMinor:result.commissionAmountMinor,receivedAt,refundPaymentId:payment.id,createdByMembershipId:ctx.membershipId,createdAt:now}).onConflictDoNothing().returning({id:outboundDealPayments.id});if(!inserted.length)throw new AccessError(409,'Denne refusjonsreferansen er allerede registrert.');}
 catch(e){if(e instanceof AccessError)throw e;if(/refund|refus|commission|payment/i.test(String(e instanceof Error?e.message:e)))throw new AccessError(409,'Betalingen er endret. Oppdater oversikten før du registrerer refusjonen på nytt.');throw e;}
 return json({ok:true});
}
