"use client";
import {useMemo,useState,useEffect} from 'react';
import Home from '../crm-client';
import {CrmApiProvider} from '@/lib/crm-api';
import {createDemoRuntime} from '@/lib/demo-crm';
import {I18nProvider,useI18n} from '@/lib/i18n/react';
import './portfolio.css';
export default function Portfolio(){return <I18nProvider locale="en"><Presentation/></I18nProvider>;}
function Presentation(){
 const {locale,setLocale}=useI18n();const en=locale==='en';
 useEffect(()=>{if(location.hash==='#thinking'){history.replaceState(history.state,'',location.pathname+location.search);document.getElementById('thinking')?.scrollIntoView();}},[]);
 const [open,setOpen]=useState(false),[version,setVersion]=useState(0);
 const runtime=useMemo(()=>createDemoRuntime(),[version]);
 if(open)return <div lang={locale}><CrmApiProvider request={runtime.request}><Home key={version} demoMode onDemoClose={()=>setOpen(false)} onDemoReset={()=>setVersion(n=>n+1)}/></CrmApiProvider></div>;
 return <div className="portfolio" lang={locale}><header className="pf-header"><a href="/portfolio" aria-label="Noracre portfolio"><img src="/noracre-logo-primary.svg" width="145" height="44" alt="Noracre"/></a><div><button type="button" onClick={()=>setLocale('nb')} aria-pressed={!en}><img src="/flags/no.svg" alt="" width="20" height="14" style={{width:20,height:14,objectFit:'fill',display:'inline-block',verticalAlign:'middle',flexShrink:0}}/> Norsk</button><button type="button" onClick={()=>setLocale('en')} aria-pressed={en}><img src="/flags/gb.svg" alt="" width="20" height="14" style={{width:20,height:14,objectFit:'fill',display:'inline-block',verticalAlign:'middle',flexShrink:0}}/> English</button></div></header>
 <main><section className="pf-hero"><div className="pf-intro"><div className="pf-eyebrow">JOAKIM FERDINAND NYGÅRD · {en?'A PERSONAL BUILD':'ET PERSONLIG PROSJEKT'}</div><h1>{en?<>A CRM built<br/><em>out of curiosity.</em></>:<>Et CRM bygget<br/><em>av nysgjerrighet.</em></>}</h1><p className="pf-lead">{en?'I built Noracre to explore what AI-assisted development can do today. A sales CRM was a natural choice: I’ve led sales teams and managed the systems they use. Building one myself gave me a way to test the technology while thinking through what a sales CRM really needs.':'Jeg bygget Noracre for å utforske hva AI-assistert utvikling kan få til i dag. Et salgs-CRM var et naturlig valg: Jeg har ledet salgsteam og hatt ansvar for systemene de bruker. Å bygge et selv ga meg muligheten til å teste teknologien og tenke gjennom hva et salgs-CRM faktisk trenger.'}</p><div className="pf-actions"><button type="button" onClick={()=>setOpen(true)}>{en?'Explore the working demo':'Utforsk den fungerende demoen'} <span aria-hidden="true">↗</span></button><button className="pf-thinking-link" type="button" onClick={()=>document.getElementById('thinking')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}>{en?'Why I built it':'Hvorfor jeg bygget det'} ↓</button></div><p className="pf-note">{en?'No sign-in. Fictional customers. Changes last only for this session.':'Ingen innlogging. Fiktive kunder. Endringer varer bare i denne økten.'}</p></div>
 <div className="pf-preview"><div className="pf-preview-caption"><span>{en?'INSIDE THE PROJECT':'INNE I PROSJEKTET'}</span><span>Noracre CRM</span></div><button type="button" className="pf-product" onClick={()=>setOpen(true)} aria-label={en?'Open the CRM demo':'Åpne CRM-demoen'}><div className="pf-product-bar"><span className="pf-product-brand">N<span>•</span></span><span>{en?'Customers':'Kunder'}</span><span className="pf-product-avatar">IB</span></div><div className="pf-product-body"><div className="pf-product-side"><span className="pf-mini-label">{en?'CUSTOMER BOOK':'KUNDEBOK'}</span><div className="pf-mini-active"><span>KR</span><div><strong>Kystlinje Regnskap</strong><small>Bergen</small></div></div><div className="pf-mini-row"><span>SB</span><div><strong>Solenga Bygg</strong><small>Trondheim</small></div></div><div className="pf-mini-row"><span>NT</span><div><strong>Nordvik Transport</strong><small>Bodø</small></div></div></div><div className="pf-product-detail"><div className="pf-mini-label">{en?'CUSTOMER CONTEXT':'KUNDEINFORMASJON'}</div><h2>Kystlinje<br/>Regnskap</h2><span className="pf-mini-stage">{en?'Contacted':'Kontaktet'}</span><div className="pf-mini-task"><span className="pf-mini-label">{en?'NEXT FOLLOW-UP':'NESTE OPPFØLGING'}</span><strong>{en?'Discuss the proposal':'Gjennomgå tilbudet'}</strong><small>Ingrid Berg · {en?'Thursday, 10:00':'Torsdag, 10:00'}</small></div><div className="pf-mini-history"><span>✓</span><div><strong>{en?'First conversation':'Første samtale'}</strong><small>{en?'Notes, people and the next step.':'Notater, personer og neste steg.'}</small></div></div></div></div><div className="pf-product-bottom"><span>{en?'Illustrative preview · Fictional data':'Illustrert forhåndsvisning · Fiktive data'}</span><strong>{en?'Try it':'Prøv selv'} ↗</strong></div></button><p className="pf-preview-note">{en?'Built with AI. Shaped by hands-on sales experience.':'Bygget med AI. Formet av praktisk salgserfaring.'}</p></div></section>
 <section className="pf-workflow" aria-label={en?'What I wanted to explore':'Hva jeg ville utforske'}>{(en?[['01','How far has AI come?','What can I actually build with today’s tools, and how much work does it take to make it function?'],['02','What makes a useful CRM?','Building it forced me to think through the essentials: customer records, activities, pipeline and follow-ups.'],['03','Learn by doing.','More CRM experience, a better understanding of the technology, and something I can keep experimenting with.']]:[['01','Hvor langt har AI kommet?','Hva kan jeg faktisk bygge med dagens verktøy, og hvor mye arbeid kreves for å få det til å fungere?'],['02','Hva gjør et CRM nyttig?','Å bygge det tvang meg til å tenke gjennom det viktigste: kundekort, aktiviteter, pipeline og oppfølging.'],['03','Lære ved å gjøre.','Mer CRM-erfaring, bedre forståelse av teknologien og noe jeg kan fortsette å eksperimentere med.']]).map(([number,title,body])=><article key={number}><span>{number}</span><h2>{title}</h2><p>{body}</p></article>)}</section>
 <section id="thinking" className="pf-thinking"><div><span className="pf-eyebrow">{en?'WHY I BUILT IT':'HVORFOR JEG BYGGET DET'}</span><h2>{en?'I wanted to understand what goes into it.':'Jeg ville forstå hva som ligger bak.'}</h2></div><div><p>{en?'Noracre started with technical curiosity. I wanted to test AI-assisted development for myself: how far the tools had come, how accessible building software had become, and what it would take to create something I could actually use.':'Noracre startet med teknisk nysgjerrighet. Jeg ville teste AI-assistert utvikling selv: hvor langt verktøyene hadde kommet, hvor enkelt det hadde blitt å bygge programvare, og hva som skulle til for å lage noe jeg faktisk kunne bruke.'}</p><p>{en?'A sales CRM felt like the right project. I’ve led sales teams and been responsible for the CRM they used. Building one made me dig deeper into my own experience and ask which components matter most, how they fit together, and what I would want from the system as a salesperson and a manager.':'Et salgs-CRM føltes som det riktige prosjektet. Jeg har ledet salgsteam og hatt ansvar for CRM-et de brukte. Å bygge et selv fikk meg til å gå dypere i min egen erfaring: Hvilke komponenter er viktigst? Hvordan henger de sammen? Hva ønsker jeg av systemet som selger og leder?'}</p><p>{en?'It’s a side project I enjoy working on. I use AI to help write and refine the code, make the decisions about what to build, and test the result. The learning is a big part of the point.':'Det er et sideprosjekt jeg liker å jobbe med. Jeg bruker AI til å skrive og forbedre koden, tar beslutningene om hva som skal bygges og tester resultatet. Læringen er en stor del av poenget.'}</p></div></section>
 <section className="pf-boundary"><h2>{en?'A real interface. A separate demo.':'Et ekte grensesnitt. En separat demo.'}</h2><p>{en?'The demo runs with its own in-memory sample data. It cannot send email, publish social posts or change production customer records.':'Demoen bruker egne eksempeldata i minnet. Den kan ikke sende e-post, publisere innlegg eller endre ekte kundedata.'}</p><button type="button" onClick={()=>setOpen(true)}>{en?'Open the demo':'Åpne demoen'} ↗</button></section></main><footer className="pf-footer">Joakim Ferdinand Nygård · Noracre <a href="mailto:jfn@noracre.no">jfn@noracre.no</a></footer></div>;
}
