"use client";
import {useMemo,useState} from 'react';
import Home from '../crm-client';
import {CrmApiProvider} from '@/lib/crm-api';
import {createDemoRuntime} from '@/lib/demo-crm';
import {I18nProvider,useI18n} from '@/lib/i18n/react';
import './portfolio.css';
export default function Portfolio(){return <I18nProvider locale="en"><Presentation/></I18nProvider>;}
function Presentation(){
 const {locale,setLocale}=useI18n();const en=locale==='en';
 const [open,setOpen]=useState(false),[version,setVersion]=useState(0);
 const runtime=useMemo(()=>createDemoRuntime(),[version]);
 if(open)return <div lang={locale}><CrmApiProvider request={runtime.request}><Home key={version} demoMode onDemoClose={()=>setOpen(false)} onDemoReset={()=>setVersion(n=>n+1)}/></CrmApiProvider></div>;
 return <div className="portfolio" lang={locale}><header className="pf-header"><a href="/portfolio" aria-label="Noracre portfolio"><img src="/noracre-logo-primary.svg" width="145" height="44" alt="Noracre"/></a><div><button type="button" onClick={()=>setLocale('nb')} aria-pressed={!en}>🇳🇴 Norsk</button><button type="button" onClick={()=>setLocale('en')} aria-pressed={en}>🇬🇧 English</button></div></header>
 <main><section className="pf-hero"><div className="pf-eyebrow">JOAKIM FERDINAND NYGÅRD · {en?'SALES LEADERSHIP × PRODUCT CURIOSITY':'SALGSLEDELSE × PRODUKTINTERESSE'}</div><h1>{en?'The next step should never get lost.':'Det neste steget skal ikke bli glemt.'}</h1><p className="pf-lead">{en?'I’ve managed sales teams and owned the CRM they worked in. Noracre is my side project exploring what happens when prospecting, customer context and follow-up live in the same workflow.':'Jeg har ledet salgsteam og hatt ansvar for CRM-et de jobbet i. Noracre er sideprosjektet mitt: en utforskning av hvordan prospektering, kundeinformasjon og oppfølging kan fungere i samme arbeidsflyt.'}</p><div className="pf-actions"><button type="button" onClick={()=>setOpen(true)}>{en?'Explore the working demo':'Utforsk den fungerende demoen'} <span aria-hidden="true">↗</span></button><a href="#thinking">{en?'The thinking behind it':'Tankene bak'} ↓</a></div><p className="pf-note">{en?'No sign-in. Fictional customers. Changes last only for this session.':'Ingen innlogging. Fiktive kunder. Endringer varer bare i denne økten.'}</p></section>
 <section className="pf-workflow" aria-label={en?'The sales workflow':'Salgsarbeidsflyten'}>{(en?[['01','Find the opportunity','Build a prospecting list and record the first conversation.'],['02','Keep the context','People, notes, activities and quotes belong with the customer.'],['03','Make the next step explicit','Set a follow-up, assign responsibility and keep the team informed.']]:[['01','Finn muligheten','Lag en prospektliste og registrer den første samtalen.'],['02','Behold sammenhengen','Personer, notater, aktiviteter og tilbud hører til kunden.'],['03','Gjør neste steg tydelig','Avtal oppfølging, fordel ansvaret og hold teamet oppdatert.']]).map(([number,title,body])=><article key={number}><span>{number}</span><h2>{title}</h2><p>{body}</p></article>)}</section>
 <section id="thinking" className="pf-thinking"><div><span className="pf-eyebrow">{en?'WHY I BUILT IT':'HVORFOR JEG BYGGET DET'}</span><h2>{en?'Sales experience, turned into product decisions.':'Salgserfaring, omsatt til produktvalg.'}</h2></div><div><p>{en?'Full-cycle salespeople have to create opportunities as well as close them. I wanted to explore a tool that helps them carry the context forward, rather than rebuild it at every handover.':'Selgere som jobber med hele salgsprosessen må både skape muligheter og avslutte salget. Jeg ville utforske et verktøy som tar sammenhengen videre, slik at den ikke må bygges opp på nytt ved hver overlevering.'}</p><p>{en?'My contribution is the sales problem, the workflows, product priorities and hands-on iteration. I used AI-assisted development to build and refine the application. This is a practical learning project alongside my sales career.':'Mitt bidrag er salgsproblemet, arbeidsflytene, produktprioriteringene og løpende utprøving. Jeg brukte AI-assistert utvikling til å bygge og forbedre applikasjonen. Dette er et praktisk læringsprosjekt ved siden av salgskarrieren min.'}</p><p>{en?'Try this: open a customer, record a call and schedule the next follow-up. Then explore the prospecting list and reporting views.':'Prøv dette: Åpne en kunde, registrer en samtale og avtal neste oppfølging. Utforsk deretter ringelisten og rapportoversikten.'}</p></div></section>
 <section className="pf-boundary"><h2>{en?'A real interface. A separate demo.':'Et ekte grensesnitt. En separat demo.'}</h2><p>{en?'The demo runs with its own in-memory sample data. It cannot send email, publish social posts or change production customer records.':'Demoen bruker egne eksempeldata i minnet. Den kan ikke sende e-post, publisere innlegg eller endre ekte kundedata.'}</p><button type="button" onClick={()=>setOpen(true)}>{en?'Open the demo':'Åpne demoen'} ↗</button></section></main><footer className="pf-footer">Joakim Ferdinand Nygård · Noracre <a href="mailto:jfn@noracre.no">jfn@noracre.no</a></footer></div>;
}
